Rakefile, src/view/config.coffee
Fix: Windowsでもビルドが通るように修正6
・d5c7508 (joinオプションの修正) で発生したWindowsでビルドできないエラーを修正
Update: bbsmenuのURLを変更した際に板一覧を自動更新する/空欄のとき、既定URLを復活させる
・bbsmenuのURLを変更した際に自動的に板一覧を更新する
・bbsmenuのURLが空欄のとき、既定URLを復活させる
お願いします
=> Fix: Windowsでもビルドが通るように修正・Update: bbsmenuのURL関連の変更

src/core/Thread.coffee
[転載禁止]©2ch.netなどやそれによるスレッドのミスを取り除くように。
よろしくお願いします。
=> Update: スレッド名に自動付加される「[転載禁止]」等を取り除く

src/core/Thread.coffee
スレッド名が空白になるのを回避
とりあえず、空白チェックで回避するようにしました
よろしくお願いします
=> Update: スレッド名に自動付加される「[転載禁止]」等を取り除く2

src/app.ts, src/core/Board.coffee, src/core/Thread.coffee, src/manifest.json, src/ui/ThreadList.coffee, src/view/board.coffee, src/view/board.haml, src/view/bookmark.coffee, src/view/bookmark.haml, src/view/config.haml, src/view/module.coffee, src/view/thread.haml
bd6812b によって次スレ検索がうまく作動していなかったので修正しました
常にdat落ちしたスレッドを表示する/しないオプション、一時的に表示する/しないボタンを追加しました
2ch.scでスレッド内のレス、板内のスレッドともにscだけを表示するボタンを追加しました
よろしくお願いします
=> Fix: 次スレ検索修正 & Update: ブックマークでdat落ちを表示しない+2ch.scでscだけを表示する

src/app.ts, src/view/config.haml, src/view/config.scss, src/write/write.coffee
＜再掲＞
こんにちは。
UA指定について掲示板ではお世話になりました。
ご教示いただいた通り、PullRequestさせていただきます。
Issue #97のコードです。
できれば、取り込んでいただけると幸いです。
仕様
・ ユーザーが記事書き込み操作を実行した時、プログラムは設定画面で指定された文字列を使用し、POST電文のHTTPヘッダ-user-agentの文字列を置き換える。
・ ユーザーは、設定画面に追加したラベル"UserAgent"のテキストエリアに、置き換え後の文字列を設定する。設定画面は下図を参照。
・ プログラムは、"UserAgent"テキストエリアが空白の場合、POST電文のHTTPヘッダを置き換えない。
[図：設定画面]
赤で囲った部分が今回追加したテキストエリア
以上、よろしくお願いします。
=> Issue #97: UA指定のコンフィグを追加する

src/core/History.coffee, src/core/WriteHistory.coffee, src/ui/Tab.ts, src/ui/ThreadContent.coffee, src/ui/ThreadList.coffee, src/view/board.haml, src/view/config.coffee, src/view/config.haml, src/view/history.haml, src/view/index.coffee, src/view/index.haml, src/view/thread.coffee, src/view/thread.haml, src/view/thread.scss, src/view/writehistory.haml
Update: タグを固定できるように
Update: SLIPが適応された表示のデザインを変更
Update: 閲覧書込履歴一覧から履歴を削除できるように ref #142
Update: スレから書込履歴を削除できるように close #142
Update: 範囲を指定して履歴を削除できるように close #121
Fix: 返信をクリックしてメニューが表示されないように
Fix: Rock54の判定をより正確に
Fix: Beアイコン/エモーティコンを2ch.scでも表示するように
Fix: 閲覧履歴削除ボタンを削除 close #113
Fix: すべてのタブを閉じるが実行できないのを修正
=> Update: タブの固定&履歴削除関連+Fix: α

Rakefile, src/common.scss, src/core/ImageReplaceDat.coffee, src/core/Thread.coffee, src/core/util.coffee, src/ui/Accordion.ts, src/ui/ThreadContent.coffee, src/ui/popup.coffee, src/ui/table_search.coffee, src/view/board.haml, src/view/bookmark.haml, src/view/bookmark_source_selector.haml, src/view/config.coffee, src/view/config.haml, src/view/history.haml, src/view/index.haml, src/view/inputurl.haml, src/view/module.coffee, src/view/search.haml, src/view/sidemenu.coffee, src/view/sidemenu.haml, src/view/sidemenu.scss, src/view/thread.coffee, src/view/thread.haml, src/view/writehistory.haml, src/write/submit_thread.haml, src/write/write.haml, src/zombie.haml
Fix: ImageReplaceDatのreplaceUrlが空のときに処理が止まるのを修正
Fix: ImageReplaceDatで空白行を無視できていなかったのを修正
Fix: ImageReplaceDatがどこかでこけると全部こけるのを修正
Fix: 設定のサムネイル表示にwikiへのリンクを追加
Fix: jQueryをslimバージョンに
※jQueryのanimation/show・hide/fadeIn・Out/slideUp・Down/ajax/非推奨は利用できなくなりました
(
* animation関連は元々利用箇所が少なかったので書いたほうが短い
* show・hideはclass操作のほうが動作が軽い
* fadeIn・Out/slideUp・Downはcssのほうが動作が軽い
* ajaxはそもそもapp.HTTPモジュールで代用可(リファクタリング予定)
* 非推奨のものは3.0アップデート時に既に削除済み
)
=> Fix: ImageReplaceDat関連&jQueryをslimバージョンに

src/app.ts, src/ui/ThreadContent.coffee, src/view/config.coffee, src/view/config.haml, src/view/thread.coffee, src/view/thread.haml
サムネイルにぼかしをかける機能を追加してみました。
app.ImageReplaceDatの呼び出しと終了確認の方法については、今後公表する可能性のある別機能との
兼ね合いより、変更をしました。
レビューをお願いします。
=> Update: 「グロ」「死ね」レスのある画像にぼかしをかける

src/ui/ThreadContent.coffee
690 名無しさん [sage] 2016/09/16(金) 09:02:46ID:q6c3H9Gc(1)
＞・H.Izawaさんの「グロ」「死ね」という返信レスがあるサムネをぼかすのを取り込み
チェック入れてないのにぼかしが入ってしまいます
read.crx 2 v1.9.1 + Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
上記の件、修正しておきましたのでよろしくお願いします。
=> Fix: ぼかしの設定を取り消してもぼかしがかかってしまう件を修正

src/ui/popup.coffee
ポップアップがマウスの左側に表示される際に、マウスの座標とポップアップがかぶっていたのを修正しました。
よろしくお願いします。
=> Fix: (popup)表示位置設定の誤りを修正(マウスの座標かぶり)

src/ui/LazyLoad.ts, src/ui/ThreadContent.coffee, src/view/thread.coffee
後続の機能追加に関連する修正群です。
コンフリクト防止のため、こちらがmergeされた後に機能追加分をプルリクする予定です。
Fix: 画像の大量ロードを防止するため、LazyLoadを一時停止する
　　スクロール時とスレッド内での検索時に無駄に画像がロードされることを防止します。
Fix: 画像がローディング表示のままになることがある現象の修正
　　ThreadContent内でのfragmentを使用した処理により、画像がローディング表示の
　　ままになってしまうことと、後の機能追加によるイベントハンドラの消失を防止します。
Fix: スレッド内検索で表示されない画像がある現象の修正
　　LazyLoad高速化対策としての座標テーブルをクリアして、表示条件の変化に対応します。
=> 画像のロードにまつわる修正

src/ui/PopupView.coffee
アクティベート対象をマウス座標より決定する
sourceとpopupのアクティベートを排他的に行う
マウスの動きが早すぎる場合にアクティベートに齟齬が生じていたようなので修正をしました。
ただし、マウスがdocumentの範囲外に出てしまった場合は画面はそのまま残ります。
(前回のプルリクとは内容が大幅に異なるため、改めてプルリクしなおしました。)
=> Fix: popupが画面に残ってしまうことがある close #211

src/app.ts, src/common.scss, src/view/config.haml, src/view/thread.coffee, src/view/thread.scss
以前サポート掲示板で公表されていたユーザーCSSを参考にして、プログラムとして機能を追加したものになります。
ユーザーCSSを元にしているため、z-indexの値についてこのままで良いのか疑問が残ります。ご意見を頂けると助かります。
補足
・サムネイルとビデオは表示サイズを別々に指定可能にしているため、拡大率についても別々に指定可能になります。
・CSSにてaタグのdisplayをinline-blockに変更してあるのは、拡大時に他の文字や画像に被らないようにするためで、a, audio, videoではbackground-color以外は共通の設定になります。
以上、よろしくお願いします。
=> 機能追加(2/4): マウスオーバーによる画像の拡大機能を追加

src/app.ts, src/core/HTTP.ts, src/core/URL.ts, src/global.d.ts, src/manifest.json, src/ui/ThreadContent.coffee, src/view/config.haml, src/view/index.coffee, src/view/thread.coffee, src/view/thread.scss
短縮URLの展開機能の追加です。
対象となるサイトは、t.coを除きヘッダのリクエストでLocation:が返ってくるものを対象にしています。
($ curl -I -i URL (linuxの場合) にて確認)
ただし、youtu.beのようなサムネイルの取得で対応可能と思われるものは含まれていません。
よろしくお願いします。
=> 機能追加(4/4): 短縮URLの展開機能を追加

src/ui/ThreadContent.coffee
画像の存在チェック処理とスクロール処理を分離した際の修正漏れにより、1ページ目のみに画像が存在していた場合に遅延スクロールが実行されていませんでした。
お手数おかけしますが、よろしくお願いします。
=> Fix: 1ページ目の画像チェックで遅延スクロールが実行されない

src/core/ContextMenus.coffee, src/manifest.json, src/view/index.coffee, src/view/module.coffee, src/view/thread.coffee, src/view/thread.haml
コンテキストメニューを拡張し、選択範囲/リンクのアドレス/画像(動画・音声)のアドレスのNG指定ができるようにしてみました。
chrome 53よりview/thread.coffeeからchrome.contextMenus.updateを実行することができなくなったため、core/ContextMenus.coffeeを新規に用意し、chrome.contextMenusのメソッドを静的メンバとして間接的に呼び出す形にしましたが、恥ずかしながら、何故こうすれば動くのかは正直なところわかっておりません。
このような不確かなものを組み込むことはできないと言うことであればPRを取り下げます。
よろしくお願いします。
=> Update: コンテキストメニューの拡張

src/view/thread.coffee
新着と未読の場合はスレッド表示時と同じくオフセットを指定したほうが見やすいと思い修正しました。
=> Fix: ジャンプパネルを使用した新着と未読へのスクロールにオフセットを指定する

src/view/thread.coffee, src/view/thread.scss
1. 「ここから新着」と「ここから未読」の表示優先順位を入れ替える。
2. スレッドのロード中はマウス・ポインタを変更することによりメッセージを表示させる。
上記2つの修正を行いました。
2.については、マウス・ポインタが通過することによりメッセージが表示されることから、コンテナに対してなんからのイベントまたは通知を送れば変化があるのではないかと思い試したものですが、理由はわかりませんが表示されるようになりました。
どっちが副作用なのかわからない修正ですが、あっても困らないかなと・・・
=> ここから新着の線が表示されない場合がある #232 の修正

src/view/thread.coffee
d5b6c12139079146007c65b87d2e19728da1abd2 のテスト中にも発生したため調べたところ #201 の原因の1つは、ThreadContentのgetReadが誤った値を戻すことまでは判明していますが、再現性が低いためその原因まではわかっていません。
d5b6c12139079146007c65b87d2e19728da1abd2 の適用後にも同じ現象が起こることがわかったので修正をしました。こちらは、勢いの速いスレでリロードを実行すると簡単に発生します。
=> Fix: リロードで既読位置がずれる refs #201

src/view/thread.coffee
・逆スクロール時の画像の位置合わせ処理が不要と判断したので廃止しました。
・コンテキストメニューの拡張時に不要なコードが残ったままだったので削除しました。
=> スクロール時の位置合わせの修正とリファクタリング

src/core/Thread.coffee
`before`の位置が間違っていた点と、`after`と`place`については2パターンあることがわかったので修正しました。
=> Fix: BBSPINKで表示がおかしくなることがある close #257

src/ui/ThreadContent.coffee
画像用コンテナの高さを可変モードにしている場合、スクロール用のアニメーション処理中に画像がロードされて座標が変更された場合に終了判定をすり抜けてしまうことがあったので修正しました。
また、ごく稀に逆方向にスクロールが実行される場合があり、ページの先頭までスクロールをし続ける現象も確認していますが、発生頻度が少ないこともあり、正確な理由まではわからなかったため、例外処理として終了判定を追加しています。
=> Fix: スレッドオープン時にスクロールが停止しないことがある

src/view/module.coffee
“常に新しいタブで開く”がonの場合は戻る/進むボタンを非表示としているが、クリック時の動作としては設定が反映されている。
“常に新しいタブで開く”がonの場合でもnet/scの切り替えを実行した場合に戻るボタンが使用可能になるが、その場合新しいタブが生成されてしまう。
本来“常に新しいタブで開く”がonの場合は使用できないはずの機能なので、設定を無視したほうが動作が自然になると思い修正しました。
=> Fix: 戻る/進むボタンの挙動を変更 close #267

src/core/Thread.coffee
別件のテスト中にたまたま踏んだリンクがbbspinkのサーバー移転後の残骸だったようで、読めないのも気持ち悪いので修正しました。
その際に見つけた以下の点も合わせて修正しました。
- パースに失敗している場合でもキャッシュを更新しようとしてエラーが発生する。
- キャッシュに残っていたデータを表示する際のメッセージが表示されない。
=> スレッド読み込み失敗時の不具合修正とbbspinkのread.cgi ver 05対応

src/view/sidemenu.coffee
bbsmenuの設定で、2ch.netと2ch.scのどちらか一方のみの設定になっている場合に無限ループが発生していました。
掲示板で報告のあった処理が重くなる現象の原因であろうと思います。
=> Fix: 板一覧の取得で無限ループの可能性があった

src/cs_addlink.coffee
2ch.netの仕様変更により、ボタンの表示が被ってしまうようになっていたので修正しました。
=> Fix: read.crx 2 で開くボタンの修正

src/view/thread.coffee, src/write/submit_thread.coffee
jqueryのバージョンアップと名前空間の違いによるものと思われますが、イベントが伝わっていなかったので以下の現象が発生していました。
- 初めて開いたスレッドの1ページ目にある画像がロードされない
- 検索にヒットした場合に画像がロードされない
- 検索中に無駄な画像のロードが発生する
LazyLoadにも伝える必要があるイベントの発火方法を`triggerHandler`から`dispatchEvent`に変更しました。
また、スレ立て時にメール欄の入力内容が反映されていなかったので修正しました。
=> thread.coffeeからLazyLoad.tsにイベントが伝わっていない

package.json
ref #292 
```
$ npm run build
$ npm run clean
$ npm run watch
$ npm run pack
```
でそれぞれ、gulpのタスクを呼び出す用にnpm-scriptsを追加。
=> Update: npm-scriptにビルド関連のコマンドを追加 ref #292

src/app.ts, src/core/ContextMenus.coffee, src/core/URL.ts, src/ui/ThreadList.coffee, src/view/config.pug, src/view/index.coffee, src/view/inputurl.coffee, src/view/module.coffee, src/view/thread.coffee
[書込履歴から該当レスへ飛べるようにする](https://github.com/readcrx-2/read.crx-2/issues/126) と、URLに指定されたレス番号へ飛べるようにする機能を追加しました。
- 書込履歴からは無条件にレス番号に飛びます。
- URLのクリック時は、デフォルトの動作を設定画面で指定し、コンテキストメニューからは逆の動作をするようにしました。
- `@href = "javascript:undefined;"`となっていた箇所は、コンテキストメニューの`targetUrlPatterns`が参照することと、該当行を削除しても動作に問題がなかったので削除しました。
=> Update: レス番号を指定してスレッドを開けるようにする

gulpfile.coffee, src/background.coffee, src/common.scss, src/core/ContextMenus.coffee, src/manifest.json, src/view/config.scss, src/view/index.coffee, src/view/thread.scss, src/write/submit_thread.scss, src/write/write.scss
chrome.tabs.create()で起動しても2重起動にはなりませんが、既に起動済みの場合にタブが一瞬出て消えるのが目障りなので、起動方法を変更しました。
コンテキストメニューについての補足
documentUrlPatterns : "<all_urls>"を指定するとread.crx自身も含まれてしまうため、スキームごとの指定にしてあります。
targetUrlPatterns : 対象パターンをできるだけ絞りたかったのですが、掲示板のURLを対象に含めると`jump.2ch.net`も含まれてしまうため、有効性チェックを追加してパターンはシンプルな形にしました。
=> ApplicationからExtensionへの移行

src/core/BBSMenu.coffee, src/core/URL.ts, src/cs_addlink.coffee, src/view/index.coffee, src/view/sidemenu.coffee, src/view/thread.coffee
携帯・スマホ・ULA版のURLをPC用のURLに変換して開けるようにしました。
`cs_addlink.coffee`内の`getURL()`がエラーになることがあります。
正規表現のちょっとした違いや比較する文字列のちょっとした違いによって発生したりしなかったりと原因がわからないため、`getURL()`の実行を評価前に移動しました。
=> Update: 携帯・スマホ用のURLをPC用URLに変換して開けるようにする close #302

src/view/config.scss
=> Fix: 設定の「関連リンク」のリンク文字列がひとつなぎに表示される close #340

src/ui/ThreadList.coffee, src/view/board.coffee, src/view/config.coffee, src/view/thread.coffee
- 勢いの速いスレなどで、ブックマークとスレッド一覧のレス数・未読数が実際と異なることがある
- 設定情報のインポートで、TextAreaへの取り込みが行われていない
以上2点の修正をしました。
=> ブックマーク・スレッド一覧及び設定画面の修正

src/core/Thread.coffee
`read.cgi ver 06`の仕様が`read.cgi ver 07`と同じになったようなので修正をしました。
全てのサーバーで同じ仕様になっているのか不明なため、念の為に旧仕様にも対応するようにしてみましたが、不要でしょうか?
bbspinkについては今のところ変更は無いようです。
=> Fix: read.cgi ver 06の仕様変更に対応

package.json, src/ui/LazyLoad.ts, src/ui/MediaContainer.coffee, src/ui/Tab.ts, src/ui/ThreadContent.coffee, src/view/config.coffee, src/view/config.pug, src/view/history.coffee, src/view/module.coffee, src/view/thread.coffee, src/view/writehistory.coffee
Update: 現在のブックマーク保存フォルダを表示するように refs #162
Update: CoffeeScript 1.12.7, TypeScript 2.4.2, fs-extra 4.0.0
Fix: 書込履歴の再読み込みができないのを修正 close #365 
Fix: 自動更新一時停止中に更新するときに通常更新時の挙動をしていなかったのを修正
Fix: 変数のところに定数が誤って入っているのを修正
Fix: リファクタリング
- Tab.ts: `Partial<>`で書くように+デフォルト引数の整理
- thread.coffee: `a < x < b`の書き方
- thread.coffee: `while i--` -> `for by -1`
- thread.coffee: `(e)`,`e.target` -> `({target})`
- 画像/動画関連処理をUI.MediaContainerに
- MediaContainer.coffee: 作成
- LazyLoad.ts: 関数の順序を変更
- 画像/動画のホバーの拡大のイベントをdelegateで
- LazyLoad.ts: それに伴い`lazyload-load`, `lazyload-load-reverse`の廃止
- LazyLoad.ts: `update()`の整理
- ThreadContent.coffee: `setImageBlur()`をMediaContainerに
- thread.coffee: `_setupHoverZoom()`の廃止
- thread.coffee: videoの再生やマウスポインタ関連イベントをMediaContainerに
- history.coffee, writehistory.coffee: `({～} = …
=> Update: 現在のブックマーク保存フォルダを表示するように+α

src/core/Bookmark.CompatibilityLayer.ts, src/ui/ThreadContent.coffee, src/view/thread.coffee
Fix: jumpResNumを共有しないように
- 初回読み込み時の`jumpResNum`と開いている状態でのジャンプの`jumpResNum`が混ざらないように分離
Fix: selectにanimate, offsetを送れるように+jumpResの処理は_drawで
- `select(target, preventScroll = false, animate = false, offset = 0)`
- `jumpRes`の処理を読み込み時のスクロールがある`read_state_attached`にするため`_draw`にわたすように
Fix: readStateAttachedフラグではなくmaybeTempを引数で渡すように
- `_draw`で初回か二回目かを`view_loaded`わたすように
- それによって`view_loaded`を整理
~~Fix: requestReloadFlagをmaybeTempで書き換え~~
- ~~`reload_request`で二回`scan`が起こる ->`maybeTemp`で書き換え可~~
- ~~**WIP**~~
- ~~**保存されないバグ**~~
うまい実装方法を思いつかなかったので諦め…
Fix: scrollToにElementを渡すこともできるように
- `scrollTo`にElement自体を渡せるように
Fix: 新着スクロールが実行されないことがあるのを修正
Fix: ブックマークにないスレの既読情報を更新しようとしたときにrejectしないように
- `catch`されませんでしたのエラー表示を減らすため
refs #342 
cc / @eru
=> Fix: thread.coffee/ThreadContent.coffeeのリファクタリング

src/ui/ThreadContent.coffee, src/ui/ThreadList.coffee, src/view/thread.coffee
【スクロールに関する修正】
・スクロールの完了に時間が掛かることがある
1. `change`の値に実数を使用しているため`scrollTop`へのセット時に小数点以下が切り捨てられ、想定数以上の回数(時間)を必要とすることがある。四捨五入を行うことにより想定数に近づけるようにする。
2. 最終レスから新着へのスクロール時に最終レスに貼られた画像がロードされると移動量が大幅に増加するが、座標補正時に`change`の再算出をしていなかった。
・スレッドのオープン時には`ThreadContent.scrollTo()`のパラメータとして、1回目(キャッシュ読み込み分)は`animate = false`, `offset = 0`を指定し、2回目(新着分)では`animate = true`, `offset = -100`を指定しているが、リロード時は2回とも`animate = true`, `offset = -100`が指定されている。その結果として、`requestAnimationFrame()`の衝突による不具合や逆方向へのスクロールが発生することがあった。リロード時も1回目は`animate = false`, `offset = 0`として実行するように変更。
・遅延スクロール前に仮スクロールを実行していたが、アニメーション処理が殆ど行われず不自然なことになっていたので、事前処理自体を廃止し、連続してアニメーション処理を行うように変更。
【その他】
1000レスを超えた場合でもID/SLIPなしのNGを有効にする
　・スレッド終端の自動追加メッセージを、日時欄の`"Over 1000 Thread"`(scの場合は`"Over 1000Thread"`)で判断するようにする。
　
スレッド一覧のレス数更新処理の誤りを修正 …
=> Fix: スレッドのオープン及びリロード時のスクロールに関する修正など

src/core/History.coffee, src/core/WriteHistory.coffee, src/core/util.coffee, src/ui/ThreadList.coffee, src/view/config.coffee
こちらは検証する時間が必要かと思い、PRを分割しました。
1. 閲覧履歴の削除が出来ていない
　一覧に表示している時間を使用して指定時間+60秒以内のデータを削除しようとしているようですが、うまく機能していないことと、想定外のデータまで削除される可能性があるため、ピンポイントで削除するように変更しました。
2. 書き込み履歴が1ヶ月ずれている
　去年の10月22日のリリース以降の問題と思われるので、それ以降のデータのリカバリーも含めました。
　ただし、新バージョンへの更新日が分からないので、スレ立て分を除いた2017年11月以降のデータのみ対象にしています。
　また、10月31日の登録分は、内部的に11月31日→12月1日と置き換わっているために、リカバリー後は11月1日になってしまうなどの問題もあります。
　リカバリーなど必要ない。履歴をまるごと捨ててしまえばいい。と言う意見ならばリカバリー処理を削除しますが・・・
あと、NG関連の修正もありますが、後日PRする予定です。
=> 閲覧履歴と書き込み履歴のバグ修正

src/core/History.coffee, src/ui/ThreadContent.coffee, src/view/board.coffee, src/view/config.coffee, src/view/history.coffee, src/view/search.coffee, src/view/thread.coffee
1. 既読位置の読み取り方法を変更
　`ThreadContent.getRead()`と`ThreadContetnt.getDisplay()`の処理方法を、Sさんには申し訳ないのですが、旧バージョンの処理方法へ変更しました。
　理由として、以下の現象の原因が`visual viewport`と`layout viewport`の違いによるものと思われることと、別件で`article`にマージンを設定すると正常に機能しなことが判ったためです。
```
188 名無しさん sage 2018/01/01(月) 16:14:11ID:NR/z4/7Q(2)
明けましておめでとうございます
いつも便利に使わせてもらっております
今年もよろしくお願いします
そして良くわからないけどついさっきスレ途中で更新したらトップに移動しちゃう不具合が勝手に直って新年早々気持ちがいい
189 名無しさん sage 2018/01/01(月) 16:46:21ID:NR/z4/7Q(2)
なんでいきなり直ったのか調べてたらいつもページを95%に縮小して使ってたんですがそれが原因だったようで100%や90%だとトップに戻らないみたいです
既出かもしれませんが修正の一助となればと幸いです
230 名無しさん sage 2018/02/01(木) 20:07:31ID:vnQO1lBs(1)
chrome 64.0.3282.119 に更新してからスレをスクロールして
読んでも未読数が減らなくなった
ページのズーム倍率を100％以外にするとダメみたい
read.crx 2 v1.22.4 + Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 …
```
=> 仕様変更及び機能追加

src/view/index.coffee, src/view/module.coffee, src/view/search.coffee, src/view/search.pug, src/view/search.scss, src/view/sidemenu.coffee
スレ検索の`https`対応が抜けていたので追加しました。
実際の検索は、`ThreadSearch.coffee`内で`https`固定で呼び出していますが、特に変更の必要がなさそうなのでそのままにしてあります。
=> Update: スレ検索のhttps対応 close #423

src/view/board.coffee, src/view/thread.coffee
したらばのSSL対応に備え、`http/https切り替えボタン`を使用可能にしました。
=> Fix: したらばSSL対応の準備 refs #419

src/ui/ContextMenu.coffee, src/ui/PopupView.coffee, src/view/thread.coffee
掲示板の書き込みを見ると、Chrome68では現象が発生していないようですが、私の方で確認した範囲内では、Windows/Linux共に特に違いが無かったので、ポップアップ内でのコンテキストメニューの表示方法を変更してみました。
見当違いの修正であれば、PRを取り下げます。
=> Fix: ポップアップ内でのコンテキストメニュー表示方法の変更 close #430

src/core/URL.ts, src/view/thread.coffee, src/view/thread.scss
- 短縮URLの対象として、`ekaz10.xyz`, `morimo2.info`, `qq4q.biz`, `u0u1.net`, `ux.nu`, `wb2.biz`を追加しました。
- あぼーん表示をする設定の場合のヘッダーの文字色を変更しました。
- ポップアップ内でのNGの扱いを、本文のあぼーん表示の設定と連動するようにしました。
なお、表示しない設定の場合はNGの件数を追加で表示します。
以上、よろしくお願いします。
=> NGの表示に関する修正と短縮URLの対象追加

src/ui/ContextMenu.coffee, src/ui/PopupView.coffee, src/view/thread.coffee
```
419名無しさんsage2018/06/24(日) 21:47:29ID:BrkUhTpU(1)
デフォルトのCSSでは、ポップアップのAA判定レス(.aa)に対して
AA向けスタイルが適用されないようです。
```
ポップアップとコンテキストメニューを修正しました。
=> Fix: ポップアップがAA表示に対応していなかったのを修正

gulpfile.coffee, src/common.scss, src/image/svg/regexp.svg, src/view/module.coffee, src/view/thread.coffee, src/view/thread.pug
スレ内検索で正規表現を使用可能にしてみました。大文字小文字の違いは無視します。
ボタンのイメージについては、フォントを指定するとファイルが巨大になるためにフォントを指定していませんので、ビルド環境によっては座標などの微調整が必要になるかもしれません。
=> Update: スレ内検索で正規表現を使用可能にする refs #125

src/app.ts, src/core/Board.coffee, src/core/ImageReplaceDat.coffee, src/core/NG.coffee, src/core/ReplaceStrTxt.coffee, src/core/Thread.coffee, src/ui/AANoOverflow.coffee, src/ui/ThreadContent.coffee, src/view/config.pug, src/view/thread.coffee, src/view/thread.scss
- `font-size`
1. `font-size`はChrome側で最小10px(ユーザー依存)
1. 最小値が取得できない かつ 小さくするためには対応が必要
- `transform:scale()`
1. そのまま拡大縮小するのでより`font-size/line-height: 16px/18px`に近くなる
1. Chromeの仕様?バク?で余白が発生
- `zoom`
1. 拡大縮小で余白は発生せず
1. 文字が荒く、再現度低
-> 実装: `transform:scale()`を使い、`margin-bottom`にマイナス値を入れることで余白は制御
AAが小さくなりすぎると文字が読めないので縮小する最小値を設定
縮小しても横幅が足りない場合、横スクロールができるように
- 定数を大文字に&オブジェクトに
- `Array::splice(0 or -1, 1)` -> `Array::pop()`, `Array::unshift()`
- `Array.from(set)` -> `[set...]`
- `delete` -> `= null`
=> Update: AAの縮小表示 refs #162+α

src/core/BBSMenu.coffee, src/core/BoardTitleSolver.coffee, src/core/util.coffee, src/view/sidemenu.coffee
Update: 板一覧更新後に板名取得テーブルが更新されるように close #447
Fix: 板名取得テーブルを複数回構築していたのを修正
Fix: 変更がない際に板一覧を構築し直さないように
Fix: 鯖移転先を板一覧から判定できていなかったのを修正
Fix: リファクタリング
=> Update: 板一覧更新後に板名取得テーブルが更新されるように close #447

src/common.scss, src/core/util.coffee, src/cs_addlink.coffee, src/ui/AANoOverflow.coffee, src/ui/Animate.coffee, src/ui/ContextMenu.coffee, src/ui/ContextMenu.scss, src/ui/Dialog.scss, src/ui/PopupView.coffee, src/ui/Tab.scss, src/ui/ThreadContent.coffee, src/ui/ThreadList.coffee, src/view/board.scss, src/view/bookmark.scss, src/view/index.coffee, src/view/index.scss, src/view/inputurl.scss, src/view/sidemenu.scss, src/view/thread.coffee, src/view/thread.scss, src/write/submit_res.coffee, src/write/write.scss
Update: 検索モード切替時に検索結果を更新するように
Fix: 長大なスレでの負荷を軽減
- Fix: CSSContainmentの設定
- DOM追加時(ポップアップなど)の再描画範囲を抑制
- Fix: 既読位置の取得時のループ回数が少なくなるように
- レス数が多いスレの場合でかつ最後のレスなどを見ている場合、250msごとにレス数分のループが回っていた->直近に見たレスの周囲からスキャンするように
Fix: AA表示/解除でAAの縮小/解除が行われていなかったのを修正
Fix: 書込履歴への追加に時間がかかっていたのを修正
Fix: 書込の名前/メール履歴が5件ではなく4件しか表示されないことがあったのを修正
Fix: 背景が黒のときに書込画面でフォーカスの表示がなかったのを修正
Fix: 「URL指定で開く」の開くボタンがつぶれていたのを修正
Fix: レス内のリンク先情報ポップアップのアニメーションが動いていなかったのを修正
Fix: テーブルの幅をより適したものに
Fix: .search_hitが検索終了時に正常に取れていなかったのを修正
Fix: thread以外もCSSContainmentを設定
Fix: リファクタリング
- `dom.style[kebab-case]` -> `dom.style.camelCase`
- `dom.style.prop = ""` -> `dom.style.prop = null`
- `while true` -> `loop`
=> Fix: 長大なスレでの負荷を軽減+α

src/ui/ThreadContent.coffee, src/view/thread.scss
Fix: スレッドでj,kでのスクロールショートカットが動作しないのを修正 close #464
Fix: 長いスレのスクロールが重いのを改善
=>  Fix: スレッドでj,kでのスクロールショートカットが動作しないのを修正 close #464+α

src/ui/Animate.coffee
Fix: Firefoxで板一覧のアコーディオンを閉じたときのチラつきをなくす
=> Fix: Firefoxで板一覧のアコーディオンを閉じたときのチラつきをなくす

src/background.coffee
- アイコンのクリックで起動しないことがある
- コンテキストメニューからの起動で「未対応のURL」となる
以上2点の修正をしました。
なお、正規表現中の`#`に対する`\`の追加ですが、実行上は無くても問題ないのですがAtomエディタの問題で表示が崩れるので追加させて頂きました。
=> Fix: アイコンのクリックでread.crxが起動しないことがある点を修正

src/core/util.coffee, src/ui/ContextMenu.coffee, src/ui/SelectableAccordion.ts, src/ui/Sortable.ts, src/ui/Tab.ts, src/ui/ThreadList.coffee, src/view/module.coffee, src/view/sidemenu.coffee, src/view/thread.coffee
- Fix: KeyboardEvent.which -> KeyboardEvent.key 
- KeyboardEvent.whichが非推奨になっていたのと、ブラウザによって値が違うことで意図した動作が起こっていなかったため refs #474 (Firefoxでコマンド入力欄が開かないのを修正)
- Fix: MouseEvent.which -> MouseEvent.button
- whichは非標準のため標準化されているbuttonに書き換え
- Fix: Firefoxで選択中の要素が画面に表示されるようスクロールされないのを修正
- `Element.scrollIntoViewIfNeeded()`はChrome独自のため、標準化されている`Element.scrollIntoView()`に書き換え
- それに伴い少し挙動が変更
=> Fix: 非推奨/ブラウザ独自プロパティ/メソッドなどの除去

src/view/index.coffee
スレッド検索で、1度もhttp/https切り替えを実行していない場合、検索結果を開くことができなかったので修正しました。
=> Fix: スレ検索で検索結果を開けないことがある

src/app.ts, src/background.coffee, src/view/board.coffee, src/view/config.coffee, src/view/index.coffee, src/view/thread.coffee, src/zombie.coffee, src/zombie.pug
- Fix: 既読情報が終了時に保存されていなかったのを修正
- zombieが起動していなかった
- ChromeとFirefoxで別の形式のウィンドウになっています(WebExtensions APIへの対応の関係)
- できるだけ目障りにならないように
- Update: Chromeで書込ウィンドウのURL欄を非表示に
- [Firefoxのバグ](https://bugzilla.mozilla.org/show_bug.cgi?id=1396881)の関係でChromeだけに
- Fix: 既定の板一覧URLを更新
- Fix: 書き込み後にエラーが出ていたのを修正
- `Failed to send onMessage rejected reply Error: Attempting to use a disconnected port object`
- mozilla/webextension-polyfill #75
- Fix: iframeからのWebExtensionAPIの呼び出しをindex.htmlからに統一
- thead.htmlからはWebExtensionAPIの呼び出しが不可能だった(原因はよくわかりません)
- config.htmlからは可能ではあったが、一応のため統一
=> Fix: 既読情報が終了時に保存されていなかったのを修正+α

src/ui/ThreadContent.coffee, src/view/thread.coffee
ローカルとブックマークの既読情報に違いがある場合に、未読数が一時的に正しく表示されなくなっていたので修正しました。
また、かつて同様の修正を行った箇所が、現在の既読情報に関する処理に対して不要になっていたので削除しました。
=> Fix: ブックマークを複数端末で共有している場合に未読数が正しく表示されていない + リファクタリング

src/core/Board.coffee, src/core/NG.coffee, src/core/Thread.coffee, src/core/URL.ts, src/ui/Tab.ts, src/ui/ThreadContent.coffee, src/ui/_Tab.scss, src/view/config.coffee, src/view/index.coffee, src/view/thread.coffee, src/view/thread.scss
- Update: ホスト名付きサードレベルドメインの掲示板も読み込めるように
- ex. http://yarufox.sakura.ne.jp/FOX
- Update: レス数でスレをNGできるように
- Update: 2chの1000レスを超えたタブに`.over1000`を付与するように
- Update: 2ch(html)のdat落ちスレを判別できるように+タブへの`.expired`の付与
- 2ch(html)だと正常にdat落ちスレも取得できるので、従来のdat落ちのエラーとは違った表示にしましたが、従来の位置である上部に青や緑などの別の色で表示するのとどちらがよいでしょう？
- Fix: WindowsのChromeで動画をフルスクリーン化しても何も表示されないのを修正 close #470
- Fix: データの削除を連打できたのを修正
- Fix: リファクタリング
=> Update: ホスト名付きサードレベルドメインの掲示板も読み込めるように+α

src/ui/ThreadContent.coffee, src/view/thread.coffee
- [876999f](https://github.com/readcrx-2/read.crx-2/commit/876999f187a71569a86919ae9d7b21bbae942477)が間違いだったので、一部修正して復活させました。
- 最終既読位置が正しく記録されない場合があったので修正しました。
=>  Fix: 最終既読位置がレスの頭に一致している場合に位置が正しく記録されていない

src/_common.scss, src/view/search.scss, src/view/writehistory.scss
- Fix: 検索結果/書込履歴のカラム省略がうまくいっていないのを修正 close #492
- Fix: 書込履歴のカラム省略を変更
- Update: Firefoxでのスクロールバーの幅と色を変更
- 色の変更を適用するにはFirefox62(現在の最新版)以降で`about:config`の`layout.css.scrollbar-colors.enabled`を`enabled`にする必要あり
- 幅の変更を適用するにはFirefox63(現在のベータ版、10/23に正式版リリース予定)以降で`about:config`の`layout.css.scrollbar-width.enabled`を`enabled`にする必要あり
---
メモ
- Chromeで有効になっている`CSS Containment`をFirefoxで利用するためには、`about:config`の`layout.css.contain.enabled`を`enabled`にする必要あり
=> Fix: 検索結果/書込履歴のカラム省略がうまくいっていないのを修正 close #492+α

src/_common.scss, src/manifest.json, src/view/config.coffee
- Fix: Firefoxで設定や履歴のエクスポートができなかったのを修正
- Fix: Firefoxのスクロールバーの色が入れ替わっていたのを修正
- +Firefoxではborderが設定できないので境界がわかるように背景を少し濃く
=> Fix: Firefoxで設定や履歴のエクスポートができなかったのを修正

src/core/Bookmark.ts, src/core/BookmarkCompatibilityLayer.ts, src/core/BrowserBookmarkEntryList.ts, src/core/DOMData.coffee, src/view/index.coffee, src/zombie.coffee
Fix: リファクタリング
- `}`と`else`の間の改行の除去
- Immutableなメソッドの後に`app.deepCopy`していたところを除去
- callback形式でWebExtensionAPIを呼び出していた箇所をPromiseに書き換え
- BrowserBookmarkEntryList.tsのメソッドをcallback形式からPromiseに書き換え
=> Fix: リファクタリング

src/_common.scss, src/view/search.coffee
- Update: 検索の追加読み込み中に"検索中"を表示するように
- Fix: 検索をリロード後にスレが開けないのを修正
- Fix: `overflow-y: auto`を既定値に
- `overflow-y: scroll`だとオーバーレイスクロールがうまく効かない
- autoでもscrollでも動作は変わらないので変更
=> Update: 検索の追加読み込み中に"検索中"を表示するように

README.md, src/background.coffee, src/core/BBSMenu.coffee, src/core/Board.coffee, src/core/Thread.coffee, src/core/URL.ts, src/cs_addlink.coffee
- Update: サブドメインなしのまちBBSに対応 close #502
- まちBBSの既読情報が消えてしまう
- Update: README.mdにMITライセンスバッジを追加
- Fix: したらばの読み込みエラーメッセージを改善
- Fix: したらばの過去ログが読み込めないのを修正
- Fix: したらばの過去ログをリロードすると重複してレスが追加されるのを修正
=> Update: サブドメインなしのまちBBSに対応 close #502+α

src/view/search.coffee, src/view/thread.coffee
```
719名無しさんsage2018/10/04(木) 17:23:55ID:5HxQgJOU(1/1)
検索して出てきたタブをhttpsに替えてread.crxを終了して
再度、起動したらhttpに戻ってしまいます
```
- 検索モードの保管タイミングを変更
保管タイミングを`unload`時ではなく、描画終了時に変更しました。
- 未読数が0になった時点で一旦既読情報を保管する
ブラウザの異常終了時などに既読情報が失われるのを少しでも防ぐため、未読数が0になったタイミングでも保管するようにしてみました。
=> Fix: 検索モードの保管タイミングを変更など

src/view/config.coffee
read.crx自体のリロードやクローズの際には`view_unload`が届かない(`index.html`より先にクローズされるため?)ので、直接`beforeunload`を受け取るようにしました。(何故か`unload`では上手く行かなかったので)
また、登録処理の2重実行を避けるために、各テキストエリアの属性に一時的な変更フラグを追加しました。
=> Fix: NGが反映されないケースがある close #507

src/app/Config.ts, src/core/BBSMenu.coffee, src/core/URL.ts, src/view/config.coffee, src/view/config/_other.pug, src/view/index.coffee
jikkyo.orgの閉鎖に伴う仕様変更を行いました。また、表示制御のためのオプションを追加しました。
wiki文案
URL
- 1行に1つのURLを指定します。
- `//`で始まる行はコメントとして無視します。
- https://egg.5ch.net/test/read.cgi/software/1339477664/ の845さんが用意された http://kyoran.php.xdomain.jp/readcrx/bbsmenu.html も使用することが出来ます。
例)
```
// 5chとbbspink
https://menu.5ch.net/bbsmenu.html
// 2ch.scとまちBBS
https://menu.2ch.sc/bbsmenu.html
// おーぷん2ちゃんねる
https://menu.open2ch.net/bbsmenu.html
// または
http://kyoran.php.xdomain.jp/readcrx/bbsmenu.html
```
メニューから除外するドメインの指定
- メニューに表示したくないドメインを1行に1つ指定します。
- `//`で始まる行はコメントとして無視します。
例)
```
// 5chは表示するがbbspinkは表示しない
bbspink.com
// まちBBSは表示するが2ch.scは表示しない
2ch.sc
```
=> 板一覧の取得に関する仕様変更

src/view/config.coffee, src/view/config/_ng.pug, src/view/config/_thumbnail.pug
- 初期値を持つ設定項目のリセットを可能にする
- キャッシュの削除ボタンにも確認画面を追加する
- 板一覧のリセットボタンに確認画面を追加する
以上、修正しました。
=> Update: 初期値を持つ設定のリセットを可能にするなど

gulp/css.coffee, gulp/plugins.coffee, package-lock.json, package.json, src/app/Config.ts, src/core/ImageReplaceDat.coffee, src/core/URL.ts
`しおり`, `ここから未読`などの表示が文字化けする現象について調べてわかったこととして
- HTML5の仕様では外部CSSファイルはCSSファイル内で`charset`を使用して文字コードを指定する必要があるらしい
- 現状ではソースに`@charset: "UTF-8";`を追加しても無視される
- gulp-sassコンパイラは文字コードを自動認識して`charset`を自動付加する説と無視される説があった
- 無視される場合の対策としてgulp-headerを使用して`@charset: "UTF-8";`を追加する方法を試したが、ShortQueryでビルドエラーが発生してしまうため`gulp-header@2.0.5`を使用する必要があることと、コンパイラのバージョンアップなどで何らかの影響が出る可能性もある
- 試しに--style-optionを変更してみたところ、`compressd`の場合にだけ`charset`が無視され、それ以外では自動認識と自動付加が行われる模様
以上より、--style-optionに`compact`を指定した後gulp-replaceで改行を削除することで、`compressed`の場合に近づけるとともに、`charset`が自動付加されるように変更しました。
現象を再現させる方法がわからないので確実に大丈夫とも言えないのですが、それなりの効果はある模様です。
また、インストールの直後、何らかの設定変更を行わないとサムネイルが表示されない件について、自動で初期化を行わせるためと設定が削除された場合の混同を避けるため、敢えて初期値を空文字列にしてみました。
間違えて削除してしまった場合などのために、設定画面にリセットボタンがあっても良いかなと思うのですが、どうでしょうか?
=> Fix: CSS疑似要素の文字化け対策など

src/write/submit_res.coffee, src/write/submit_thread.coffee, src/write/write.coffee
- Fix: Chrome72～でリファラエラーで書き込めないのを修正
[chrome.webRequest - Google Chrome](https://developer.chrome.com/extensions/webRequest#event-onBeforeSendHeaders)
> Starting from **Chrome 72**, the Set-Cookie response header is not provided and **cannot be modified or removed without specifying 'extraHeaders'** in opt_extraInfoSpec.
- Fix: User-Agentがついていない/Refererが最初からついている場合でも書き込みが正常にできるように修正
=> Fix: Chrome72～でリファラエラーで書き込めないのを修正

src/app.ts, src/app/Callbacks.ts, src/app/Config.ts, src/app/Defer.ts, src/app/Log.ts, src/app/Message.ts, src/app/Util.ts, src/core/Bookmark.ts, src/core/BookmarkEntryList.ts, src/core/BrowserBookmarkEntryList.ts, src/core/HTTP.ts, src/core/URL.ts, src/core/Util.ts, src/global.d.ts, src/shortQuery.d.ts, src/ui/Accordion.ts, src/ui/LazyLoad.ts, src/ui/SearchNextThread.ts, src/ui/SelectableAccordion.ts, src/ui/Sortable.ts, src/ui/Tab.ts, src/ui/ThreadContent.coffee, src/ui/VirtualNotch.ts, src/view/config.coffee
- Fix: .tsの全般的なリファクタリング
- `var` -> `let`/`const`
- 関数の戻り値が`void`/`Promise<void>`の場合は省略(それ以外は明記)に統一
- 関数や`if`/`for`などのブロックのスペースを統一
- 変数の宣言位置の統一
- 再代入すべきでないプロパティに`readonly`を付加
- 外から操作しないプロパティに`private`を付加
- 不要な`self = this`を除去
- Fix: リファクタリング
- `app.getAll()`が文字列ではなくオブジェクトを返すように
- `UI/Tab.ts`のオブジェクトの型を改善
- `UI.Tab.historyStore`を`Object`から`Map`に変更
- `app.deepCopy()`の型を改善
- Fix: `app.Bookmark.removeAll()`と`removeAllExpired()`が常に`true`を返していたのを修正
- Fix: タブ履歴の重複エントリが消えていなかったのを修正
- Fix: 一部の短縮URLの展開に失敗する場合があるのを修正
- Twitterの短縮URLは展開後のURLに`HEAD`で取得すると`GET`では存在していても`403`が返ってくる
- Fix: Rock54などが表示されているレスで展開された短縮URLの位置がずれているのを修正
- `短縮URL -> Rock54表示 -> 短縮URL展開表示`の順になっていた
あけましておめでとうございます。今年もよろしくお願いします。
新年から大きなプルリクですが…
=> Fix: .tsのリファクタリング&バグ修正

gulp/other.js, src/background.js, src/manifest.json, src/write/cs_write.js
fixed https://github.com/readcrx-2/read.crx-2/issues/545
manifest v3への対応
- ガイド
- https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/
- https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
- https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/
- ざっくりしたルールを定義しておいて、updateSessionRulesで書き換えることになりそう
- https://github.com/MartinWie/Framer#technical-words 参考になる
- https://developer.chrome.com/docs/extensions/reference/browserAction/
- https://developer.chrome.com/docs/extensions/reference/action/
=> Update: manifest v3への対応
