readcrx-2/read.crx-2

Rakefile
src/common.scss
src/ui/Sortable.scss
src/ui/Tab.scss
src/ui/contextmenu.scss
src/ui/dialog.scss
src/ui/table_search.scss
src/ui/ui.scss
src/view/board.scss
src/view/bookmark.scss
src/view/bookmark_source_selector.scss
src/view/config.scss
src/view/history.scss
src/view/index.scss
src/view/inputurl.scss
src/view/search.scss
src/view/sidemenu.scss
src/view/thread.scss
src/write/write.scss

scss,hamlの文字コード関連エラーの対処。
よろしくお願いします。

Fix: Windowsでもビルドが通るように修正1

---

README.md
Rakefile

2 : ImageMagick周辺のwindowsとlinuxのコマンド記法の違いの対処。
3 : jquery周辺のビルド周辺のパス関連エラーを対処。
残り:`sh "git apply ../jquery_delegate_middle_click.patch"`のエラー
何度もすいません…
お願いします。

Fix: Windowsでもビルドが通るように修正2・3

---

Rakefile

git applyのwhitespace関連エラーの対処。
お願いします。

Fix: Windowsでもビルドが通るように修正4

---

Rakefile

ImageMagickの二度実行しないと作動しない謎現象・うまく出力できていない現象の対処。
修正しました。お願いします。

Fix: Windowsでもビルドが通るように修正5

---

Rakefile
lib/jquery_delete_map.patch
src/view/module.coffee

動作には問題ないですが、
Chrome等のブラウザの開発者ツール用のjquery.min.mapへのリンクが、
jquery.min.jsの入っていてエラーが出ていたので、リンクを削除しました。
お願いします。

Fix: jquery.min.mapを読みに行っているのを修正/Update: 2chのみに切り替えを表示

---

Rakefile
src/common.scss
src/ui/Sortable.scss
src/ui/Sortable.ts
src/ui/Tab.scss
src/ui/contextmenu.scss
src/ui/dialog.scss
src/ui/table_search.scss
src/ui/ui.scss
src/view/board.scss
src/view/bookmark.scss
src/view/bookmark_source_selector.scss
src/view/config.scss
src/view/history.scss
src/view/index.coffee
src/view/index.scss
src/view/inputurl.scss
src/view/search.scss
src/view/sidemenu.scss
src/view/thread.coffee
src/view/thread.scss
src/write/write.scss

Fix: 文字コード指定をソースではなくビルドファイル内のコマンドのオプションとして記述
Update: タブをダブルクリックすることで更新できるように
よろしくお願いします

Fix: リファクタリング & Update: タブをダブルクリックで更新できるように

---

README.md
Rakefile
src/app.ts
src/test/app.Bookmark.ChromeBookmarkEntryList.spec.coffee
src/test/test_app.bookmark.coffee
src/ui/ThreadList.coffee
src/view/board.coffee
src/view/board.scss
src/view/bookmark.coffee
src/view/bookmark.scss
src/view/module.coffee
src/view/search.coffee
src/view/search.scss
src/view/thread.scss

Fix: ビルドファイルのapp.jsの削除が作動していなかったことを修正
Fix: Windowsでもrake packが通るよう修正
Fix: Windowsでclamscanに対応
Fix: リファクタリング
Fix: 検索してマッチしたすべてのスレが非表示だったとき何も適合しなかったと表示するよう修正
よろしくお願いします

Fix: app.jsの削除&Windowsでもrake packが通るように修正&clamscanに対応&リファクタリング

---

src/app.ts
src/core/Thread.coffee
src/view/config.haml
src/view/thread.coffee

Fix: 細かい設定抜けを修正
Update: スレの自動更新を実装
Update: スレの何もないところをダブルクリックすると更新できるように
よろしくお願いします

Update: スレの自動更新&スレの何もないところをダブルクリックで更新 & Fix: 細かい設定

---

src/app.ts
src/view/config.coffee
src/view/config.haml
src/view/config.scss
src/view/thread.coffee

Update: 見ているスレのみを自動更新する設定を追加
Update: 設定のインポート/エクスポート機能を追加
Fix: リファクタリング
よろしくお願いします

Update: 見ているスレのみを自動更新する設定・設定のインポート/エクスポート機能

---

src/view/config.coffee

Fix: 設定インポートを非同期処理化
よろしくお願いします

Fix: 設定インポートを非同期処理化

---

src/manifest.json
src/view/thread.coffee

Fix: 自動更新がすべてのタブで適応されていたのを修正
同じバグを何度も直したつもりをやってしまってすみません…
よろしくお願いします

Fix: 自動更新がすべてのタブで適応されていたのを修正

---

src/core/History.coffee
src/core/read_state.coffee
src/view/bookmark.coffee
src/view/config.coffee
src/view/config.haml
src/view/module.coffee

Fix: dat表示切替ボタン関連のリファクタリング
Update: 閲覧履歴のインポート/エクスポート機能の追加
よろしくお願いします

Update: 閲覧履歴のインポート/エクスポート機能の実装

---

README.md
src/app.ts
src/core/Thread.coffee
src/view/board.coffee
src/view/config.haml
src/view/search.coffee
src/view/thread.coffee

速くなりそうなパースを書いたけれどうまく動作しなかったのでとりあえずコメントアウト

Update: 履歴を保存しないオプションを追加 closed #57&Fix: 新しい形式のパースを追加

---

README.md
src/app.ts
src/core/Thread.coffee
src/view/board.coffee
src/view/config.haml
src/view/search.coffee
src/view/thread.coffee

速くなりそうなパースを書いたけれどうまく動作しなかったのでコメントアウト

Update: 履歴を保存しないオプションを追加&Fix: 新しい形式のパースを追加

---

src/core/Thread.coffee

Fix: 2番レスが消えるのを修正

---

src/view/thread.coffee

Fix: BBSPINKでレス番号をクリックしても返信メニューが出ないのを修正 #81

---

src/ui/ThreadContent.coffee

Fix: しおりの位置がNG対象のレスの時表示がずれるのを修正 #37

---

src/ui/ThreadContent.coffee

Update: NG除外機能を実装 close #39

---

src/core/Thread.coffee

Fix: 一部板でレス番がずれるのを修正（暫定対応）

---

src/core/thread_search.coffee
src/ui/ThreadList.coffee

Fix: 2chの検索が効かないのを修正

---

Rakefile
src/core/Thread.coffee
src/view/thread.coffee
src/view/thread.scss
src/write/write.coffee
src/write/write.haml

Update: 投稿の名前・メールをプルダウンに close #105
Fix: 書き込み日時が1つずれるのを修正 close #123
Fix: キャッシュが壊れるのを修正 ref #112
Fix: 投稿したときのobも色付けするように

Fix: 書き込み日時が1つずれるのを修正/キャッシュが壊れるのを修正

---

src/app.ts
src/core/Thread.coffee
src/core/WriteHistory.coffee
src/manifest.json
src/ui/ThreadContent.coffee
src/view/board.haml
src/view/bookmark.haml
src/view/bookmark_source_selector.haml
src/view/config.coffee
src/view/config.haml
src/view/empty.haml
src/view/history.haml
src/view/index.coffee
src/view/index.haml
src/view/inputurl.haml
src/view/module.coffee
src/view/search.haml
src/view/sidemenu.haml
src/view/thread.coffee
src/view/thread.haml
src/view/writehistory.haml
src/write/write.coffee

Fix: 書込履歴が日付順に並ばないのを修正
Fix: 名前欄のsmallタグが効くように修正
Fix: トリップ付きの名前でもうまくプルダウンに表示されるように
Fix: X-Frame-Optionsの非推奨化に対応
Fix: レスがずれるのを修正
Fix: Revert 38b2e08

Fix: 書込履歴が日付順に並ばない/名前欄のsmallタグ/トリップ付きの名前のプルダウン/レスがずれる

---

Rakefile
src/app.ts
src/core/Board.coffee
src/core/Thread.coffee
src/manifest.json
src/ui/Tab.ts
src/ui/ThreadContent.coffee
src/view/board.coffee
src/view/board.haml
src/view/config.haml
src/view/index.coffee
src/view/module.coffee
src/view/thread.coffee
src/view/thread.haml
src/write/cs_write.coffee
src/write/submit_thread.coffee
src/write/submit_thread.haml
src/write/submit_thread.scss
src/write/write.coffee
src/write/write.haml

Update: read.cgi ver05での高速化
Fix: open2chの板取得の高速化
Update: 2ch.scとopen2ch.netに書き込みできるように close #132
Update: 2ch.net/2ch.sc/BBSPINK/したらば/open2chのスレ立て機能を追加
Update: マウスホイールでタブを切り替えるかどうかの設定を追加
Update: 書込履歴を後から追加できるように close #122
Update: したらばの文字色変化に対応

Update: 書き込み/スレ立て関連+α

---

src/app.ts
src/ui/ThreadContent.coffee
src/view/board.coffee
src/view/config.coffee
src/view/config.haml
src/view/config.scss
src/view/index.coffee
src/view/module.coffee
src/view/thread.coffee
src/view/thread.haml
src/view/thread.scss
src/write/submit_thread.coffee

Update: 書込履歴を保存しないオプションを追加
Update: ﾜｯﾁｮｲ/IPアドレス/トリップのポップアップに対応 close #93
Update: SLIP/トリップをコピーを追加
Update: Rock54の表示を変更
Fix: 書込履歴をインポートできないのを修正	
Fix: 書込履歴に手動で後から追加すると一ヶ月ずれるのを修正
Fix: configのデザイン微調整

Update: 書込履歴を保存しないオプション+ﾜｯﾁｮｲ/IP/トリップのポップアップ etc

---

src/ui/ThreadContent.coffee
src/view/thread.coffee
src/view/thread.scss

Fix: IPの指定をミスってるのを修正
Fix: ID/SLIPの表示を修正
Fix: 書込履歴に後から追加したときに表示が即時に変わるように close #136
Fix: dat落ち時に読み込み失敗するまで時間かかるのを修正

Fix: 書込履歴に後から追加したときに表示が即時に変わるように etc.

---

Rakefile
src/app.ts
src/core/Board.coffee
src/core/NG.coffee
src/ui/Tab.ts
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/board.haml
src/view/config.coffee
src/view/config.haml
src/view/module.coffee
src/view/thread.coffee
src/view/thread.haml
src/view/thread.scss

Update: SLIPのNGに対応 close #140
Update: 選択範囲をNG指定できるように close #143
Update: NGを連鎖させれるように close #43
Update: 自分に対してのレスを強調するように close #115
Fix: 起動時にタイトルがおかしい場合があるのを修正 close #149
Fix: タブバーの何もないところを右クリックしてもメニューが出ないのを修正
Fix: NG機能のリファクタリング+高速化 close #144
Fix: 既読情報削除ボタンを復元 close #113

Update: SLIP/選択範囲のNG・連鎖NG・返信レス強調+Fix: 起動時にタイトルがおかしい/NG機能の高速化

---

src/core/BoardTitleSolver.coffee
src/core/ImageReplaceDat.coffee
src/core/Thread.coffee
src/core/URL.ts
src/core/thread_search.coffee
src/core/util.coffee
src/ui/ThreadContent.coffee
src/ui/contextmenu.coffee
src/ui/dialog.coffee
src/ui/popup.coffee
src/ui/table_search.coffee
src/view/board.coffee
src/view/bookmark_source_selector.coffee
src/view/config.coffee
src/view/search.coffee
src/view/search.haml
src/view/search.scss
src/view/thread.coffee
src/view/thread.haml
src/view/thread.scss
src/write/submit_thread.coffee
src/write/write.coffee

Update: サムネイルのファビコンをどのURLでも表示するように	
Fix: 未読ブックマークが表示されないのを修正 close #155
Fix: 検索の板名を日本語に
Fix: 検索で"検索中"が表示されないのを修正	
Fix: 2ch.sc/したらば/まちBBSのスレの読み込みの高速化
Fix: スレタイの<mark></mark>を表示しないように
Fix: Beの表示がおかしいのを修正

Update: サムネイルのファビコンをどのURLでも表示するように	+α

---

LICENSE
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/config.coffee
src/view/config.haml
src/view/index.coffee
src/view/thread.coffee

Fix: 書込履歴を保存しないが機能しなかったのを修正
Fix: 自動スクロール中に自動スクロールすると自動スクロールが止まらないのを修正
Fix: 新着レスが少ないときに自動スクロールが解除されないのを修正
Fix: datをインポートしても保存されないのを修正

Fix: 自動スクロール関連+α

---

Rakefile
package.json
src/core/Board.coffee
src/core/History.coffee
src/core/Thread.coffee
src/ui/ThreadContent.coffee
src/ui/popup.coffee
src/view/board.haml
src/view/bookmark.haml
src/view/bookmark_source_selector.haml
src/view/config.haml
src/view/history.haml
src/view/index.haml
src/view/inputurl.haml
src/view/search.haml
src/view/sidemenu.haml
src/view/thread.coffee
src/view/thread.haml
src/view/writehistory.haml
src/write/submit_thread.coffee
src/zombie.haml

Fix: 2ch互換掲示板の一部が閲覧できないのを修正
Fix: ポップアップが特定条件下で表示されないのを修正 close #161
Update: ShortQuery.jsを導入

Fix: 2ch互換掲示板の一部が閲覧できない&ポップアップが特定条件下で表示されないのを修正

---

src/ui/ThreadContent.coffee
src/view/module.coffee
src/view/thread.coffee
src/write/submit_thread.haml
src/write/write.haml

Fix: Windowsでオートスクロールが利くように
Fix: 書込画面が正常に動作しないのを修正

Fix: Windowsでオートスクロールが利くように&書込画面が正常に動作しないのを修正

---

src/ui/LazyLoad.ts
src/view/thread.coffee

ポップアップ画面に重たいgifなどがあった場合に少し気になっていたので修正しました。
あってもなくてもいいようなものですみませんが、レビューお願いします。

Fix: popup画面でもloadingアニメーションを表示するように修正

---

src/ui/popup.coffee
src/view/thread.scss

現在ポップアップの高さが固定になっているので、内容に合わせて自動調整するように変更しました。
また、その際にCSSバラメータの指定でおかしな箇所があったので合わせて修正しました。
なお、現在作業中の案件で<video>要素を含むと確実に表示が崩れることが判明したので、
popupの処理については全面的に書き換えを行っています。(新規でPopupView.coffeeを追加)
基本的な動作と表示の入れ子現象が起きないことは確認済みですが、完成にはもう少し時間がかかります。
そちらが完成すればこのプルリクは意味はありませんが、一応、作業報告ということで・・・

popup画面の修正

---

src/ui/popup.coffee

先日のpopup画面の修正で、表示位置の設定に誤りがあったので修正しました。
お手数おかけしますが、よろしくお願いします。

Fix: (popup)表示位置設定の誤りを修正

---

src/app.ts
src/core/Notification.coffee
src/manifest.json
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/board.coffee
src/view/bookmark.coffee
src/view/bookmark.scss
src/view/config.coffee
src/view/index.coffee
src/view/module.coffee
src/view/thread.coffee
src/view/writehistory.scss
src/write/submit_thread.coffee
src/write/write.coffee

Update: ブックマークに板名を追加
Fix: 通知をクリックすると閉じるように close #189
Fix: chrome.extensionsの非推奨メソッドを除去 close #188
Fix: 検索で変換中の文字は無視するように

Update: ブックマークに板名を追加&Fix

---

src/ui/PopupView.coffee
src/ui/ThreadList.coffee
src/view/thread.coffee

popupの表示位置の修正、検索ボックスで日本語入力確定時に検索を開始する

---

src/ui/PopupView.coffee

Fix: popupでのbox-shadowの値取得用正規表現を修正 close #208

---

src/view/index.coffee
src/view/thread.coffee

Fix: レス選択時の右クリックメニューが動作しないのを修正 close #207,#191

Fix: レス選択時の右クリックメニューが動作しないのを修正 close #207,#191

---

src/app.ts
src/common.scss
src/ui/LazyLoad.ts
src/ui/ThreadContent.coffee
src/view/bookmark.scss
src/view/config.coffee
src/view/config.haml
src/view/config.scss
src/view/index.coffee

Update: 更新可能かを通知するように close #209
Update: 画像ぼかしのキーワードを任意に設定できるように close #190
Fix: 設定を開いたままread.crxを閉じたときにNGなどが適用されないのを修正
Fix: LazyLoadの最適化 close #176

Update: 画像ぼかしのキーワードを任意に設定できるように+更新可能かを通知するように&Fix

---

src/view/config.coffee

画像の大きさ指定の方には組み込んでありますが、ぼかしの設定にも影響があるので分離しました。
不要ならば破棄してください。

設定のインポートでrangeの値が更新されていなかった

---

src/view/index.coffee

Fix: 更新可能の通知が繰り返す表示されるのを修正 close #218

---

src/core/URL.ts
src/view/config.coffee

・設定のインポート時にnumberの値が反映されていなかった。
・短縮URLに`redd.it`を追加。
以上2点、修正しました。

設定画面と短縮URLの修正

---

src/app.ts
src/ui/PopupView.coffee
src/view/config.haml

以下のリファクタリングを含みます
・関数名と変数名のキャメルケースの統一
・複数行にまたがるif文の成形
・コメント文の先頭に空白を挿入
ポップアップの表示タイミングを遅らせて、無駄なポップアップの出現を減らせるようにしてみました。
よろしくお願いします。

Update: ポップアップのディレイ表示機能を追加

---

src/view/thread.coffee

・画像のロードによるスクロールで新着などの位置がずれることがある
・複数環境でブックマークを共有するとスクロールが実行されない
上記の修正を行いました。よろしくお願いします。

Fix: read_state_attacheの修正 fixed #232

---

src/view/thread.coffee

Fix: read_state_attacheの修正

---

src/view/thread.coffee

Fix: ジャンプパネルで新着のオフセットが設定されていなかった

---

Rakefile
package.json
src/app.ts
src/core/Bookmark.CompatibilityLayer.ts
src/core/HTTP.ts
src/core/ImageReplaceDat.coffee
src/core/NG.coffee
src/core/ReplaceStrTxt.coffee
src/global.d.ts
src/ui/ThreadContent.coffee
src/view/config.coffee
src/view/config.haml
src/view/module.coffee

Update: ReplaceStrTxtの実装 close #236
Update: Typescriptを2.1.4にアップデート
Update: CoffeeScriptを1.12.2にアップデート

Update: ReplaceStrTxtの実装 close #236

---

src/core/Thread.coffee

Fix: BBSPINKのスレッド読み込みに失敗する close #251

---

src/core/Thread.coffee

2chのhtmlの仕様に変更があったようなので修正をしました。
全てのスレッドが同じなのかわからないため、新仕様に一致しない場合は旧仕様でのマッチングを行うようにしています。

Fix: 2chのスレでレス番がずれる close #258

---

src/ui/ThreadContent.coffee

Fix: お絵描き機能のサムネイルが表示されない close #261

---

package.json
src/app.ts
src/core/Board.coffee
src/core/Bookmark.ChromeBookmarkEntryList.ts
src/core/Thread.coffee
src/core/URL.ts
src/core/read_state.coffee
src/core/util.coffee
src/global.d.ts
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/ui/VirtualNotch.ts
src/view/board.coffee
src/view/bookmark.coffee
src/view/config.coffee
src/view/index.coffee
src/view/search.coffee
src/view/thread.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Update: Typescript 2.2.2
Update: coffeescript 1.12.5
Fix: リファクタリング
Fix: mousewheel->wheelイベント
Fix: ブックマークのdat落ち表示がされてなかったのを修正
Fix: 設定のinputのバリデーションがおかしかったのを修正

Fix: リファクタリング & バグ修正

---

src/core/Thread.coffee
src/core/util.coffee

cgi ver 07 では、dat落ちスレの読み込みが出来ないようで、そのままだとサーバー移転の可能性がありますとのメッセージが表示されてしまうため、サーバー移転判定部の一致条件を若干修正しました。

Fix: read.cgi ver 07.0.0に対応する close #271

---

src/core/Thread.coffee

Fix: read.cgi ver 07の仕様変更に対する修正

---

src/ui/ThreadContent.coffee

read.cgi ver 07.0.1対応の修正をしました。
ID用のタグが新設されたようですが、それを利用するのは修正が大変そうなので特に意識していません。

Fix: read.cgi ver 07.0.1対応

---

src/core/URL.ts
src/global.d.ts

- 短縮URLに、kkbox.fm, ur2.link, cos.lv, urx.red, ur0.work, ur0.biz, ustre.am を追加。
- 短縮URLのキャッシュに対応。

短縮URLの追加とキャッシュ対応

---

src/core/ImageReplaceDat.coffee
src/ui/LazyLoad.ts
src/ui/ThreadContent.coffee
src/view/module.coffee

Update: ImageReplaceDatをlazyloadするように
Fix: リファクタリング

Update: ImageReplaceDatをlazyloadするように

---

src/ui/LazyLoad.ts

Fix: ビルドできないのを修正 close #287

---

src/core/Thread.coffee
src/core/URL.ts
src/cs_addlink.coffee
src/view/thread.coffee

Fix: したらばの過去ログに対応 close #264

---

Rakefile
src/common.scss
src/image/svg/pause.svg
src/ui/ThreadList.coffee
src/view/board.coffee
src/view/board.haml
src/view/bookmark.coffee
src/view/bookmark.haml
src/view/module.coffee
src/view/thread.coffee
src/view/thread.haml

Update: スレ本文のフィルタリングを更新時にも保持するように close #49
Update: スレ一覧のフィルタリングを更新時にも保持するように close #48
Update: 自動更新の一時停止ボタンを追加 close #76
-> close #75

Update: フィルタリングを更新時にも保持するように

---

src/core/Thread.coffee

Fix: dat形式での読み込みが出来ない件を修正

---

src/core/History.coffee
src/core/WriteHistory.coffee
src/ui/LazyLoad.ts
src/ui/Tab.ts
src/ui/VirtualNotch.ts
src/view/history.coffee
src/view/writehistory.coffee

Fix: タブが切り替えられないのを修正
Fix: サムネのファビコンが表示されないのを修正
Fix: 履歴/書込履歴が古いものを表示していたのを修正

Hotfix: タブが切り替えられないのを修正+α

---

Rakefile
src/ui/LazyLoad.ts
src/ui/Tab.ts
src/ui/TableSorter.coffee
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/ui/VirtualNotch.ts
src/view/config.coffee
src/view/index.coffee

Fix: タブ同士の伝達がうまくいっていなかったのを修正
・スレを下まで表示した後に未読数がゼロにならなくなりました（何回開いても未読数の変化なし）
・複数タブ表示時SHIFT+Wで閉じたあとに一度スレ内部をクリックしないとSHIFT-Wでスレを閉じられなくなりました
Fix: サムネイルがホバーで拡大できないのを修正
Fix: 板などの右クリックメニューが出ないのを修正
Fix: 背景色が黒のときに自動更新一時停止ボタンが表示されないのを修正
Fix: 設定で履歴を出力できないのを修正
Fix: 設定で履歴が削除できないのを修正
Fix: リファクタリング
・CustomEvent->Event
・非推奨のEvent生成を除去

Hotfix: 既読が反映されないのを修正

---

src/write/submit_thread.coffee

・タイトルと本文が送信されない
・エラーメッセージを閉じると書き込み画面が空白になる
・書き込みに成功してもスレッドが開かない
・書き込みに成功しても画面が自動で閉じない
上記の不具合があったので修正しました。

Fix: スレ立ての不具合修正

---

Rakefile
package.json
src/app.ts
src/common.scss
src/core/util.coffee
src/global.d.ts
src/ui/Tab.scss
src/ui/Tab.ts
src/ui/ThreadList.coffee
src/ui/contextmenu.scss
src/view/board.haml
src/view/bookmark.haml
src/view/history.haml
src/view/index.coffee
src/view/index.haml
src/view/index.scss
src/view/module.coffee
src/view/search.haml
src/view/thread.coffee
src/view/thread.haml
src/view/writehistory.haml
src/zombie.coffee
src/zombie.haml

Update: 右クリックメニューの並び替えをしやすいように close #46
Update: キーボードショートカットでレス/スレ立てができるように refs #162 awef#173
Fix: 開き方が正常に動作していなかったのを修正 refs #248
Fix: zombie.htmlが起動していなかったのを修正
Fix: zombie.htmlが正常に実行できていないのを修正
Fix: hitcountが正常に動作していないのを修正
Fix: 復元されないタブが生じる場合があるのを修正 refs #162 awef#165
Fix: 新規インストール後に設定を一度も開かずスレを開くと読み込みに失敗するのを修正 close #294
Fix: 検索ボックス内の入力文字とヒット数文字列が重ならないように refs #162 awef#101
Fix: ショートカット一覧にフォーカスがずれないのを修正
Fix: キーボードショートカットからクリックができないのを修正
Fix: リファクタリング
・@types/jqueryの除去
・ソースマップの出力をしないように
・awef#13 のパッチの解除

Fix: 各種バグ修正+α

---

src/view/sidemenu.coffee

Fix: 板一覧の取得で無限ループの可能性があった(再)

---

src/app.ts
src/core/util.coffee
src/view/index.coffee

告知メッセージの表示機能を追加してみました。
バージョンはいくつにされるつもりか分からないので、取り敢えず"2.0.0"未満の場合に表示するようにしてあります。
また、メッセージの表示は3日に一回で最大3回までにしてあります。

Update: 告知メッセージの表示機能を追加 refs #141

---

src/app.ts
src/common.scss
src/shortQuery.d.ts
src/zombie.coffee

Fix: zombieが閉じないことがあるのを修正
Fix: 背景が黒のときに検索欄の表示が変になるのを修正

Fix: zombieが閉じないことがあるのを修正+α

---

src/ui/ThreadContent.coffee
src/write/cs_write.coffee

- 書込終了後、スレのリロードが完了しない
- 書込履歴に反映されない
- スレ立てでエラーメッセージが表示されない
以上の修正を行いました。

open2ch関係のバグ修正

---

README.md
src/manifest.json
src/view/config.pug
src/view/index.coffee
src/view/thread.coffee

- #313 readcrx-2.github.io へのリンクをhttps化する
- #314 更新通知時のリンク先にアンカーを付与する

Update: refs #313, #314

---

gulpfile.coffee
src/app.ts
src/core/Bookmark.ChromeBookmarkEntryList.ts
src/core/Bookmark.CompatibilityLayer.ts
src/core/Bookmark.ts
src/core/HTTP.ts
src/core/URL.ts
src/ui/LazyLoad.ts
src/ui/Sortable.ts
src/ui/Tab.ts

Fix: strictNullChecksをtrueに
Fix: noImplicitThisをtrueに

Fix: Typescriptをより厳格に

---

src/app.ts
src/view/bookmark.coffee
src/view/bookmark.scss

Update: ブックマーク更新の高速化とリファクタリング close #299

Update: ブックマーク更新の高速化とリファクタリング close #299

---

src/ui/PopupView.coffee

Fix: popupViewのEventがremoveできていない close #321

---

src/ui/PopupView.coffee

Fix: popupViewのEventがremoveできていない(再)

---

src/app.ts
src/core/Thread.coffee
src/core/URL.ts
src/ui/ThreadContent.coffee
src/ui/contextmenu.coffee

Fix: 右クリックメニューがはみ出ないように refs #199
Fix: app.tsのlog関連の型を指定
Fix: app.tsのリファクタリング
Fix: スレのパースの高速化
Fix: リファクタリング

Fix: 右クリックメニューがはみ出ないように refs #199 & リファクタリング

---

src/core/URL.ts
src/view/module.coffee

Fix: 2ch.scへの切り替えが効かない板がある close #332

---

src/app.ts
src/common.scss
src/core/Cache.coffee
src/core/HTTP.ts
src/ui/Tab.scss
src/ui/Tab.ts
src/view/board.coffee
src/view/bookmark.coffee
src/view/bookmark.scss
src/view/config.coffee
src/view/config.pug
src/view/history.coffee
src/view/history.scss
src/view/index.coffee
src/view/module.coffee
src/view/search.scss
src/view/sidemenu.scss
src/view/thread.coffee
src/view/thread.scss
src/view/writehistory.coffee
src/view/writehistory.scss
src/write/submit_thread.coffee
src/write/write.coffee

Fix: 中クリックでChromeのタブが開いてしまうのを修正 refs #248
Fix: ～.2ch.netの人気スレのNGがngobjと違っていたのを修正
Fix: リファクタリング
・インポート/エクスポート
・自動更新のリファクタリング
・:before, :after -> ::before, ::after

Fix: 中クリックでChromeのタブが開いてしまうのを修正+α

---

src/core/Board.coffee
src/core/URL.ts
src/core/util.coffee
src/ui/LazyLoad.ts
src/ui/ThreadContent.coffee
src/ui/VirtualNotch.ts
src/view/bookmark.coffee
src/view/index.coffee
src/view/sidemenu.coffee
src/view/thread.coffee

Fix: ポップアップ制御がクリックのときにIDをクリックするとメニューが表示されるのを修正 close #345
Fix: スレのタブを閉じたときに左隣のタブではなく板がフォーカスされているのを修正 close #344
Fix: サーバー移転エラーが出ないのを修正
Fix: ブックマークの既読情報の反映に失敗しているのを修正
Fix: ブックマークの初回並び替えが正しく動作していないのを修正
Fix: リファクタリング
・passiveEventListener
・ThreadContent.addItem
・classList.add->addClass
・Board.coffeeのscFlg
・書き込み可能かの判定

Fix: サーバー移転エラーが出ないのを修正+α

---

src/ui/ThreadContent.coffee
src/view/thread.coffee

Fix: 正常に開けないスレッドがある

---

package.json
src/core/Board.coffee
src/core/ImageReplaceDat.coffee
src/core/NG.coffee
src/ui/ThreadContent.coffee
src/view/bookmark.coffee
src/view/config.coffee
src/view/index.coffee
src/view/module.coffee
src/view/search.coffee
src/view/sidemenu.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Fix: 返信(n)が表示されないことがあるのを修正
Fix: リファクタリング
Update: coffeescript 1.12.6, typescript 2.4.0, sharp 0.18.1

Fix: 返信(n)が表示されないことがあるのを修正

---

src/view/board.coffee

板のスレ一覧を表示した時にブックマークの既読情報が反映されていないのが気になっていたので修正してみました。
ワンテンポ遅れて未読数が書き換わるのが気になりますが、確認した範囲内では正しく表示されているようです。
これで問題ないでしょうか?

Fix: スレッド一覧の未読数にブックマークの既読情報が反映されていない

---

src/view/config.coffee
src/write/submit_thread.coffee
src/write/write.coffee

https接続時に2ch.scで書き込みが出来ない件を修正しました。
chromeから直接書き込みを行っても「Error! リファラってやつをご存知ですか？(1)」となるので、2ch.sc側のバグの可能性もあり、再修正が必要になるかもしれません。
設定画面でbbsmenuのリセットが効かなかったので修正しましたが、ShortQueryの使い方が良く分かっていないので間違っているかもしれません。

Fix: https & 2ch.sc の不具合修正と設定画面の不具合修正

---

src/core/ContextMenus.coffee
src/view/thread.coffee

Fix: コンテキストメニューの「レス番号を無視してリンクを開く」が使えない close #350

---

src/core/Thread.coffee
src/view/history.coffee
src/view/thread.coffee
src/view/writehistory.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Update: 閲覧・書込履歴を無限に遡れるように close #187
Fix: 一度「更新失敗」が出ると正常に更新されても表示が消えないのを修正
Fix: zombieが起動しない可能性があるのを修正
Fix: リファクタリング

Update: 閲覧・書込履歴を無限に遡れるように close #187 & Fixes

---

src/ui/ThreadList.coffee
src/view/module.coffee
src/view/thread.coffee
src/view/writehistory.pug

書込履歴からレス番号を無視して開く方法が無かったので追加しました。

Update: 書込履歴にも「レス番号を無視してリンクを開く」を追加 & リファクタリング

---

src/core/History.coffee
src/view/history.coffee
src/view/history.pug
src/view/index.coffee
src/view/thread.coffee
src/view/thread.scss

Update: 重複する履歴を最新のみ表示するボタンを追加
Fix: 引用して返信時に改行がなくなるのを修正 close #362
Fix: スレを閉じたときのフォーカス遷移がうまく動作しないことがあるのを修正 close #359
Fix: 自己レスしたときに返信の色ではなく書込の色になるように close #360
Fix: 検索中に更新をすると読み込み中のままになるのを修正
Fix: リファクタリング

Update: 重複する履歴を最新のみ表示するボタンを追加+α

---

src/app.ts
src/view/board.coffee
src/view/index.coffee
src/view/module.coffee
src/view/thread.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Update: 書込/スレ建てウィンドウの位置を保存するように
Fix: 忍法帖復元ボタンの修正

Update: 書込/スレ建てウィンドウの位置を保存するように+

---

src/ui/LazyLoad.ts
src/ui/ThreadContent.coffee
src/view/thread.coffee

`IntersectionObserver`
参考
- https://blog.jxck.io/entries/2016-06-25/intersection-observer.html
- https://developer.mozilla.org/ja/docs/Web/API/Intersection_Observer_API
- https://www.chromestatus.com/feature/5695342691483648
Fix: リファクタリング
- LazyLoad.ts: IntersectionObserverで書き換え
- ThreadContent.coffee: getBoundingClientRectを利用するように
- thread.coffee: readStateAttachedをloadCountで書き換え
- Revert "Fix: readStateAttachedフラグではなくmaybeTempを引数で渡すように"
- バグがあったのでrevertの上実装しなおし
- thread.coffee: フッター表示処理をIntersectionObserverで書き換え
P.S. これをマージ後リリースしますー

IntersectionObserver & getBoundingClientRect

---

src/common.scss
src/ui/LazyLoad.ts
src/ui/Tab.scss
src/ui/Tab.ts
src/ui/contextmenu.scss
src/ui/dialog.scss
src/view/bookmark.scss
src/view/config.scss
src/view/history.coffee
src/view/history.pug
src/view/index.coffee
src/view/index.scss
src/view/module.coffee
src/view/thread.coffee
src/view/thread.scss

Fix: スレなどがread.crxで開けないのを修正
Fix: 自動更新一時停止ボタンが動作しないのを修正
Fix: 「同じものは最新をひとつだけ表示」を既定に close #371
Fix: タブが保存されないことが少なくなるように refs #370
Fix: SCSS変数の一部をCSS変数に

Fix: スレなどがread.crxで開けない&自動更新一時停止ボタンが動作しないのを修正+α

---

src/core/thread_search.coffee
src/ui/MediaContainer.coffee
src/view/thread.coffee

Fix: 更新でレスがぼかしにひっかかるときに画像をぼかす処理を実行できていなかったのを修正(再)close #375
Fix: 「&」などをスレ検索できないのを修正
Fix: スレ検索で`&`などのエンコードがデコードされていなかったのを修正

Fix: bug fixes

---

src/app.ts
src/common.scss
src/core/Board.coffee
src/core/Bookmark.CompatibilityLayer.ts
src/core/URL.ts
src/core/util.coffee
src/global.d.ts
src/manifest.json
src/ui/ContextMenu.scss
src/ui/TableSorter.coffee
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/bookmark.coffee
src/view/config.coffee
src/view/index.coffee
src/view/index.scss
src/view/module.coffee
src/view/search.coffee
src/view/search.pug
src/view/sidemenu.coffee
src/view/sidemenu.scss
src/view/thread.coffee
src/view/thread.scss
src/write/submit_thread.coffee
src/write/write.coffee

Update: 検索でもソートできるように
Fix: 最後に/のない板も読み込めるように
Fix: スレを読み込めませんでしたの表示のCSSが効いていないのを修正
Fix: エラーしたときにサーバー移転していないものでもサーバー移転エラーが出るのを修正
Fix: offsetHeight is 0ではなくdisplay:noneを見るように
Fix: Chromeの要求バージョンを54以上に変更
Fix: ブックマークでソートできないのを修正(#381 でのバグの修正漏れ)
Fix: リファクタリング
- `setScheme()`をwrite/submit_thread.coffeeでも
- `BroadcastChannelAPI`で書き換え
- `-webkit-user-select` -> `user-select`

Update: 検索でもソートできるように+α

---

src/view/board.coffee
src/view/module.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Fix: スレ一覧を更新するとスレの未読数の表示が消えるのを修正
Fix: スレッド一覧表示のソート順が実際のものと連動しないのを修正 close #389
Fix: 書き込み後に自分のレスが表示されないことが少なくなるように

Fix: バグフィックス

---

src/core/BoardTitleSolver.coffee
src/ui/ThreadList.coffee

Fix: 板一覧にない板の名前が取得できないのを修正 close #394
Fix: 板名が取得できなかったスレをブックマークに追加してもすぐには表示されないのを修正 close #395

Fix: #394 & #395

---

gulpfile.coffee
package-lock.json
package.json
src/app.ts
src/background.coffee
src/core/BBSMenu.coffee
src/core/Board.coffee
src/core/BoardTitleSolver.coffee
src/core/Bookmark.CompatibilityLayer.ts
src/core/Thread.coffee
src/core/ThreadSearch.coffee
src/core/util.coffee
src/manifest.json
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/board.coffee
src/view/bookmark.coffee
src/view/config.coffee
src/view/history.coffee
src/view/index.coffee
src/view/search.coffee
src/view/thread.coffee
src/view/writehistory.coffee
src/write/write.coffee

Fix: 未読ブックマークの未読数が表示されないのを修正
Fix: ブックマークのスレッドに更新失敗が付き続けるのを修正 close #397
Fix: .isComposingで書き換え 最低Chromeバージョンを56へ引き上げ
Fix: typo
Coffeescript2
- Update: Coffeescript2の導入
-  - Fix: coffeescript2の非互換性の修正
- Fix: async/awaitで書き換え
-  - Fix: 同期XHRを使用しないように

Update: Coffeescript2(&async/await)+Fix: バグ修正

---

README.md
src/background.coffee
src/core/BBSMenu.coffee
src/core/Board.coffee
src/core/BoardTitleSolver.coffee
src/core/ReadState.coffee
src/core/Thread.coffee
src/core/ThreadSearch.coffee
src/core/URL.ts
src/core/util.coffee
src/cs_addlink.coffee
src/manifest.json
src/ui/ThreadContent.coffee
src/view/board.coffee
src/view/module.coffee
src/view/search.coffee
src/view/thread.coffee
src/write/cs_write.coffee
src/write/submit_thread.coffee
src/write/write.coffee

メモ
・検索がIPv6環境だとうまく動かない（かもしれない）ということを明記すること

Update: 5ch.netへの対応 close #399

---

src/core/Cache.coffee
src/core/History.coffee
src/core/ReadState.coffee
src/core/Thread.coffee
src/core/WriteHistory.coffee
src/core/util.coffee

Fix: レス数が飛ぶのを修正 close #401
Fix: indexeddb関連をasync/awaitで書き換え

Fix: レス数が飛ぶのを修正 close #401 + α

---

gulpfile.coffee
package-lock.json
package.json
src/core/Board.coffee
src/core/Thread.coffee
src/view/thread.coffee
src/zombie.coffee

Fix: 再読み込み直後などに書き込むとレスを読み込まないのを修正 close #406
Fix: リファクタリング
Update: Typescript 2.5.3 & others
Fix: gulpfileをasync/awaitで書き換え

Fix: 再読み込み直後などに書き込むとレスを読み込まないのを修正 close #406 + α

---

gulpfile.coffee
src/core/BBSMenu.coffee
src/core/Board.coffee
src/core/BoardTitleSolver.coffee
src/core/Cache.coffee
src/core/History.coffee
src/core/ImageReplaceDat.coffee
src/core/NG.coffee
src/core/Thread.coffee
src/core/URL.ts
src/core/WriteHistory.coffee
src/core/util.coffee
src/view/config.coffee
src/view/index.coffee
src/view/module.coffee
src/view/sidemenu.coffee

Update: `:w18,21`とすると`>>18>>21`という返信ができるように
Fix: scのスレ一覧が開けないのを修正 close #409
Fix: エスケープされている文字のNGがうまく動かないのを修正
Fix: 履歴/書込履歴のhttpsマークが表示されていないのを修正
Fix: typescriptの出力にasync/awaitのポリフィルが入ってたのを除去
Fix: リファクタリング
・app.BBSMenuをpromiseに
・app.Cacheをキャメルケースに

Update: `:w18,21`とすると`>>18>>21`という返信ができるように+α

---

src/core/Board.coffee
src/core/Thread.coffee
src/ui/ThreadContent.coffee
src/view/thread.coffee
src/view/thread.scss

Fix: 書込履歴に記録されないのを修正
Fix: open2ch.netの板/スレを開けないのを修正
Fix: メールの前後の[]をCSSに
Update: 日付をtimeタグで囲うように

Fix: 書込履歴に記録されないのを修正+α

---

src/app.ts
src/core/HTTP.ts
src/core/URL.ts
src/ui/LazyLoad.ts
src/ui/ThreadContent.coffee
src/view/config.coffee
src/view/history.coffee
src/view/module.coffee
src/view/thread.coffee
src/view/writehistory.coffee

Fix: IDの表示がうまくいっていないのを修正
Fix: リファクタリング

Fix: IDの表示がうまくいっていないのを修正

---

src/core/Thread.coffee
src/ui/ThreadContent.coffee
src/view/module.coffee

バグ対応のうち簡単なものと、bbspinkの仕様変更分です。
bbspinkは普段使用していないので正確ではありませんが、おそらくキャッシュの削除が必要になると思います。
また、5chについても、旧バージョンと新バージョンでキャッシュの内容が若干異なることになるので、削除したほうが良いかと思います。
ブックマークマネージャの仕様変更がいつからなのか分からないのですが、おそらく61か62くらいからだと思います。
よろしくお願いします。

バグ修正とbbspinkの仕様変更対応

---

src/core/NG.coffee

Fix: NG関連のバグ修正

---

gulpfile.coffee
package-lock.json
package.json
src/core/BBSMenu.coffee
src/core/Board.coffee
src/core/BoardTitleSolver.coffee
src/core/Bookmark.ChromeBookmarkEntryList.ts
src/core/URL.ts
src/core/util.coffee
src/image/svg/star.svg
src/ui/ThreadContent.coffee
src/view/board.coffee
src/view/index.coffee
src/view/search.coffee
src/view/sidemenu.coffee
src/view/thread.coffee

Update: URL変換を5ch.net関連の追加
Update: gulp 4.0.0
Fix: 2chの鯖移転検出をbbsmenuからできていなかったのを修正
Fix: スレの読み込みの高速化
Fix: リファクタリング
- serverinfoの処理のリファクタリング
- gulpfileのリファクタリング

Fix: 2chの鯖移転検出をbbsmenuからできていなかったのを修正+α

---

src/core/BoardTitleSolver.coffee
src/core/Cache.coffee
src/core/History.coffee
src/core/WriteHistory.coffee
src/core/util.coffee
src/view/thread.scss

Fix: レスのヘッダーのスペースがなくなっているのを修正 close #432

Fix: レスのヘッダーのスペースがなくなっているのを修正 close #432

---

src/core/util.coffee
src/view/config.pug

Fix: 次スレ検索に失敗するのを修正
Update: 公式/非公式サポートBBSへのリンクをhttpsに

 Fix: 次スレ検索に失敗するのを修正

---

src/core/Board.coffee
src/core/Cache.coffee
src/core/History.coffee
src/core/ReadState.coffee
src/core/Thread.coffee
src/core/WriteHistory.coffee
src/core/util.coffee
src/view/module.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Fix: 板移転先が検出できていなかったのを修正
Fix: スレの板検出後読み込みが止まっていたのを修正
Fix: キャッシュの部分削除ボタンが正常に削除できていなかったのを修正
Fix: 文字参照のデコードで一部の場合に意図していない値を出していたのを修正
Fix: リファクタリング
- ReadState.coffeeのリファクタリング
- History/WriteHistory.coffeeのリファクタリング

Fix: 板移転先が検出できていなかったのを修正+α

---

package-lock.json
package.json
src/core/URL.ts
src/core/util.coffee
src/cs_addlink.coffee
src/manifest.json
src/ui/NextThreadSearch.ts
src/ui/ThreadContent.coffee
src/view/config.coffee
src/view/config.pug
src/view/config.scss
src/view/thread.coffee
src/write/cs_write.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Update: 設定のタブ化
Update: パー速や実況サロンfreeに書き込めるように close #206
Update: パー速や実況サロンfreeの板名が表示されるように
Update: 次スレ検索で現在のスレで出てきたURLのスレはより上のほうに表示されるように
Update: CoffeeScript 2.3.1+α
Fix: したらばのTRIPがパースできていなかったのを修正
Fix: リファクタリング

Update: 設定のタブ化+外部掲示板関連

---

src/core/ReplaceStrTxt.coffee
src/core/URL.ts
src/view/config.pug

Update: Jane総合掲示板の板名が表示されるように
Fix: ReplaceStr.txtでallを指定すると適用されないのを修正
Fix: ReplaceStr.txtの読み込みができないのを修正

Fix: ReplaceStr.txt関連修正

---

src/app.ts
src/ui/ThreadContent.coffee
src/view/config.pug
src/view/thread.coffee

返信数のカウントが遅くならない方法を考えてみました。
その分NG処理の負荷は若干上がりますが・・・

Update: NGを返信に含めない機能を追加

---

src/core/BoardTitleSolver.coffee
src/core/ThreadSearch.coffee
src/core/util.coffee
src/view/config.coffee
src/view/config.pug
src/view/config.scss
src/view/search.coffee
src/view/sidemenu.coffee
src/view/sidemenu.pug

Update: 板一覧からブックマークに追加/解除できるように refs #162
Update: 「、」区切りのアンカーに対応
Update: 削除後も件数を表示するように
Update: 設定のデザインの微調整
Update: スレ検索を最初は20件だけ表示するように refs #162
Fix: スレ検索時の板名取得で無駄に通信していたのを修正
Fix: リファクタリング

Update: 板一覧からブックマークに追加/解除できるように+α refs #162

---

src/app.ts
src/view/bookmark.coffee
src/view/config.pug

Update: ブックマークのソート順を保持できるように close #195
Fix: 設定のその他の整理

Update: ブックマークのソート順を保持できるように close #195+α

---

src/background.coffee
src/core/Util.ts
src/core/util.coffee

Update: 全角記号なども検索の際そろえるように
Fix: 次スレ検索の高速化
Fix: リファクタリング

Update: 全角記号なども検索の際そろえるように+α

---

package-lock.json
package.json
src/app.ts
src/core/Cache.coffee
src/core/NG.coffee
src/core/Thread.coffee
src/core/URL.ts
src/cs_addlink.coffee
src/shortQuery.d.ts
src/ui/AANoOverflow.coffee
src/ui/NextThreadSearch.ts
src/ui/PopupView.coffee
src/ui/SelectableAccordion.ts
src/ui/Sortable.ts
src/ui/Tab.ts
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/bookmark_source_selector.coffee
src/view/index.coffee
src/view/module.coffee
src/view/thread.coffee
src/write/cs_write.coffee
src/write/submit_res.coffee
src/write/write.coffee

Update: ShortQuery.js 1.0.3
Fix: 副NGワードが効いていないのを修正
Fix: リファクタリング

Fix: 副NGワードが効いていないのを修正

---

src/core/util.coffee
src/cs_addlink.coffee
src/ui/ThreadContent.coffee

Fix: 「read.crx2で開く」が表示されないのを修正
Fix: 名前欄にaタグがそのまま表示されるのを修正
リンクがつかないようにしましたが、つけたほうがいいでしょうか？

Fix: 「read.crx2で開く」が表示されないのを修正

---

src/core/Bookmark.ChromeBookmarkEntryList.ts
src/ui/Tab.ts
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/bookmark_source_selector.coffee
src/view/config.coffee
src/view/config.pug
src/view/index.coffee
src/view/inputurl.coffee
src/view/module.coffee
src/view/thread.coffee
src/write/cs_write.coffee
src/write/write.coffee

Update: localstorageの最大値の表示を追加
Update: indexeddb/localstorageの容量メーターの追加
Fix: 新着の「何個目の書き込みか」がずれていたのを修正
Fix: 重複ブックマークを統合するように close #18
Fix: デフォルトの名前/メールアドレスが動作していなかったのを修正
Fix: 書き込み画面のエラーを閉じれなかったのを修正
Fix: DAT落ちスレをブックマークに追加時DAT落ち表示がつかなかったのを修正
Fix: リファクタリング
- window.postMessageも`structured-clonable type`を渡せたのでJSONに変換せずオブジェクトをそのまま渡すように書き換え

Fix: 新着の「何個目の書き込みか」がずれていたのを修正+α

---

src/cs_addlink.coffee
src/ui/ThreadList.coffee
src/view/module.coffee
src/write/submit_res.scss

Fix: 「read.crx2で開く」が表示されないのを修正
Fix: 背景が黒のときに書込画面のドロップダウンの▼が明るいのを修正
Fix: 「未読スレをすべて開く」した際にスレのタイトルがデコードされてなかったのを修正 close #456
Fix: 検索からブックマークに追加したときにレス数がブックマークで表示されなかったのを修正

Fix: 「未読スレをすべて開く」した際にスレのタイトルがデコードされてなかったのを修正 close #456+α

---

src/view/index.scss
src/view/thread.scss

Fix: canaryで設定/ショットカットキーヘルプが開けないのを修正
Fix: canaryでポップアップが表示されないのを修正

Fix: canaryで動かない箇所があるのを修正

---

src/core/Bookmark.ts

Fix: ブックマークの既読などのレス数の更新と削除ができないのを修正

---

src/common.scss
src/core/Bookmark.CompatibilityLayer.ts
src/core/Thread.coffee

以下の修正をしました。
- スレッドを開いただけではブックマークのレス数が更新されない。
- ブックマーク及びスレ一覧の未読数が-1になることがある。
- 一部の入力域などでブラウザのフォント設定が反映されない。(Chromeのバグ?)

ブックマークとフォントに関する修正

---

src/view/config.coffee
src/view/index.coffee
src/view/module.coffee

Fix: メモリリークしていた箇所を修正
~~(最後のコミット以外は #462 に含まれてます)~~

Fix: メモリリークの一部を修正 refs #311

---

src/cs_addlink.coffee

Fix: read.crxで開くをクリックしても反応がないのを修正

Fix: read.crxで開くをクリックしても反応がないのを修正

---

src/background.coffee
src/core/ContextMenus.coffee
src/core/Thread.coffee
src/core/URL.ts
src/view/index.coffee
src/view/module.coffee
src/view/search.coffee
src/view/sidemenu.coffee

Update: 対応していないURLのエラーを出すように
Fix: スレ検索のドロップダウンによる並び替えができないのを修正
Fix: 履歴からスレ検索を開くと「検索:null」が開かれるのを修正
Fix: 携帯URLが開けないのを修正
Fix: 携帯URL変換を5chのもので行うように
Fix: キーボードショートカットのヘルプが開かなくなることがあるのを修正 close #469
Fix: Firefoxでアイコンクリック時の動作がおかしかったのを修正
Fix: Firefoxでコンテキストメニューが追加されていなかったのを修正

Fix: バグ修正 close #469

---

src/ui/MediaContainer.coffee

レイアウトへの影響も考えたら、何とも泥臭い方法になってしまいました・・・

Fix: Firefoxでzoomが使えない件を修正 close #473

---

src/core/History.coffee
src/core/WriteHistory.coffee
src/manifest.json

Fix: IndexedDBでputよりaddのほうが適切なので変更
Fix: Firefoxのupdate_urlがjsonではなくxmlになっていたのを修正

Fix: Firefoxのupdate_urlがjsonではなくxmlになっていたのを修正+α

---

src/_common.scss
src/background.coffee
src/core/BoardTitleSolver.coffee
src/core/util.coffee
src/ui/ThreadContent.coffee

- Update: テーブルをスクロールするときに吸いつくように
- Chrome69～のみ対応ですが、多少使い勝手がよくなる程度なのとFirefoxも今後対応するはずなのでPolyfillとかは入れてません
- Fix: 板名の取得に失敗するのを修正
- Fix: スレ内に登場したスレが次スレ判定での上位にきやすすぎたのを修正
- Fix: IDとSLIPが入れ替わっていたのを修正
- Fix: リファクタリング

Fix: 板名の取得に失敗するのを修正+α

---

src/ui/ThreadContent.coffee

NG判定されたレスからのぼかし判定を無効に出来るようにしました。

Update: NGレスによるぼかし判定を無視出来るようにする close #485

---

src/view/board.coffee
src/view/thread.coffee
src/view/thread.scss

Fix: Vivaldiでは書き込みウィンドウをタブで開けるように
Fix: ポップアップにも`dat落ちしたスレッドです`が表示されるのを修正
Vivaldi側にバグ報告をしてきたのでそれが修正されるまでとりあえず

Fix: Vivaldiでは書き込みウィンドウをタブで開けるように

---

src/_common.scss
src/app.ts
src/ui/LazyLoad.ts
src/ui/MediaContainer.coffee
src/view/config.pug
src/view/module.coffee
src/view/thread.coffee

- Update: スクロールバーをブラウザ既定のものにできるように
- Update: dat落ちスレで次スレ検索ボタンが表示されるように refs #162
- Update: クリックでサムネイルを読み込めるように

Update: クリックでサムネイルを読み込めるように+α refs #162

---

src/zombie.coffee

- Fix: Vivaldiでzombieが閉じないことがあるのを修正

Fix: Vivaldiでzombieが閉じないことがあるのを修正

---

src/manifest.json
src/ui/VirtualNotch.ts
src/view/config/_data.pug
src/write/cs_write.coffee
src/write/submit_res.coffee
src/write/write.coffee

Update: まちBBSに書き込めるように
Fix: Firefoxでタブをホイールで切り替えるときにたくさんホイールを回す必要があるのを修正
Fix: 書き込み失敗後に無駄なリロードが起きていたのを修正
Fix: 「履歴を保存しない」の文字列をクリックして切り替えられなかったのを修正

Update: まちBBSに書き込めるように+α

---

src/app/Callbacks.ts
src/core/util.coffee
src/write/submit_res.coffee
src/write/submit_thread.coffee
src/write/write.coffee

Fix: app.Callbacks.destroy()が正常に動作していなかったのを修正
Fix: app.Writeのリファクタリング

Fix: リファクタリング

---

src/app/Util.ts
src/core/Bookmark.ts
src/core/BookmarkEntryList.ts
src/core/BrowserBookmarkEntryList.ts
src/core/Notification.coffee
src/core/ReadState.coffee
src/core/util.coffee
src/ui/Dialog.coffee
src/view/board.coffee
src/view/config.coffee
src/view/config/_data.pug
src/view/thread.coffee
src/write/submit_thread.coffee

ChromeとFirefox間でのデータ移行用に、ブックマークと既読情報をImport/Export可能にしてみました。

Update: ブックマークのインポートとエクスポートを可能にする & その他

---

src/view/config.coffee

Fix: dat落ち削除を実行すると削除ボタンが消えてしまう

---

src/view/config/_reload.pug
src/view/thread.coffee
src/view/thread.pug

Update: jumppanelに最新50を追加

---

src/write/write.coffee

Fix: 書き込みタイムアウトのメッセージが表示されていなかった

---

src/ui/ThreadContent.coffee

Fix: 一つのレスにSLIP変更とRock54が同時に存在したときにデザインがおかしいのを修正

Fix: 一つのレスにSLIP変更とRock54が同時に存在したときにデザインがおかしいのを修正

---

gulp/img.coffee
gulp/plugins.coffee
package-lock.json
package.json
src/_base.pug
src/app.ts
src/core/Board.coffee
src/core/BookmarkEntryList.ts
src/core/BrowserBookmarkEntryList.ts
src/core/URL.ts
src/ui/LazyLoad.ts
src/ui/SearchNextThread.ts

Fix: 板/スレのブックマーク/解除時にエラーが出るのを修正 close #515
Fix: 板の読み込みでtimeoutするとエラーせず止まるのを修正 close #516
- 応急処置的
- 場所によって`try-catch`を`if null`なり`if result.error?`で置き換えていくのがよいと思われ
Fix: リファクタリング
- `.ico`の廃止(faviconを`png`に変更)
- `optional catch`

Fix: #515 & #516

---

src/core/Board.coffee
src/core/Thread.coffee
src/view/config.coffee
src/write/submit_res.coffee

Fix: プロキシエラーで書き込めないのを修正
Fix: 設定などのエクスポート時にメモリリークしていたのを修正
Fix: 板のキャッシュが表示されるときに延々と読み込み表示になるのを修正
Fix: スレでタイムアウトした際にエラーが発生しないのを修正

Fix: プロキシエラーで書き込めないのを修正

---

gulp/config.coffee
package-lock.json
package.json
src/app/Log.ts
src/core/Bookmark.ts
src/core/BookmarkEntryList.ts
src/core/BrowserBookmarkEntryList.ts
src/core/URL.ts
src/global.d.ts
src/ui/Accordion.ts
src/ui/LazyLoad.ts
src/ui/SearchNextThread.ts
src/ui/SelectableAccordion.ts
src/ui/Sortable.ts
src/ui/Tab.ts
src/ui/VirtualNotch.ts
src/view/thread.scss
src/write/write.coffee

Fix: 書き込みウィンドウのAA確認表示が表示できないのを修正
Fix: ポップアップ内の画像を拡大した際に画像が一部表示されないことがあるのを修正
Fix: WebExtentsionsの型定義ファイルを追加

Fix: 書き込みウィンドウのAA確認表示が表示できないのを修正+α

---

src/core/BBSMenu.coffee
src/core/Board.coffee
src/core/BoardTitleSolver.coffee
src/core/BookmarkEntryList.ts
src/core/BrowserBookmarkEntryList.ts
src/core/History.coffee
src/core/ReadState.coffee
src/core/Thread.coffee
src/core/ThreadSearch.coffee
src/core/URL.ts
src/core/WriteHistory.coffee
src/core/util.coffee
src/ui/ThreadContent.coffee
src/ui/ThreadList.coffee
src/view/board.coffee
src/view/bookmark.coffee
src/view/index.coffee
src/view/inputurl.coffee
src/view/module.coffee
src/view/search.coffee
src/view/sidemenu.coffee
src/view/thread.coffee
src/write/submit_res.coffee
src/write/submit_thread.coffee
src/write/write.coffee

fixされているURLなのかそうじゃないのかが不明瞭なのと、
何度も何度も同じパースがされているので(`getTsld()`など)
クラスにしました

Fix: リファクタリング(app.URL.URL)

---

src/core/ThreadSearch.coffee

とりあえずコメントアウトで別のところでの検索に対応
depends on #531 
(#531 のマージ後にブランチ切りなおしてマージします)

Fix: スレ検索の仮修正

---

src/core/URL.ts
src/view/board.pug
src/view/config/_info.pug
src/view/module.coffee
src/view/thread.coffee

- Update: 板のnet/sc切り替えができるように
- Update: 板のタイトルとURLをコピーできるように
- Fix: まちBBSのスレが読めないのを修正
- Fix: したらばの過去ログが見れないのを修正
- Fix: 公式サイト/サポートBBSのディレクトリ削除/休止に伴いリンクを削除
- Fix: リファクタリング

Update: 板のnet/sc切り替えができるように+α

---

package-lock.json
package.json
src/view/bookmark.coffee

はじめまして。
Bookmark のインポートした後にエラーが出たので、簡単な Null Check を追加しました。
ビルドしたときにエラーが出たので、依存ライブラリのバージョンを変更していますが、問題があればそちらは除いてもOKです。
よろしくお願いいたします。

Bookmark import  Null Check

---

src/ui/ThreadList.js

:bug: 検索対象のカラム変更時に検索が実行されないのを修正

---

src/core/Thread.js

UPDATE: read.cgi ver 08系の対応
